"""Distinct, editable laboratory specifications for lessons 26a through 46.

Solutions are source-side verification assets, not learner notebook cells.
"""

from textwrap import dedent, indent


def _check(body, repair=False):
    function = "test_repair" if repair else "test_exercise"
    flag = "repair_complete" if repair else "exercise_complete"
    return (f"def {function}():\n" + indent(dedent(body).strip(), "    ")
            + f"\n\n{flag} = {function}()\n"
            + f'print("PASS" if {flag} else "INCOMPLETE: complete the TODO first")\n')


def _lab(*, torch_setup=True, **fields):
    fields = {name: dedent(value).strip() for name, value in fields.items()}
    imports = ("import math\nimport torch\ntorch.set_num_threads(1)\n"
               "torch.manual_seed(17)\n") if torch_setup else "import math\n"
    fields["setup"] = imports + fields["setup"]
    fields["check"] = _check(fields.pop("checks"))
    fields["fix_check"] = _check(fields.pop("fix_checks"), repair=True)
    return fields


EXERCISES = {
    "26a-sequence-models": _lab(
        title="دو گذشته، یک Token آخر",
        goal="نشان دهید ترتیب پنجره کجا حفظ می‌شود و کجا از دست می‌رود.",
        prerequisite="ورودی سه‌محوری، Linear و نسخهٔ v1 را بشناسید.",
        predict="دو پنجره از بردارهای یکسان ولی با ترتیب معکوس داریم. میانگین آن‌ها و خروجی یک خوانش خطیِ پنجره‌ای را پیش‌بینی کنید.",
        setup='''
        from mini_gpt.stages.v1 import TokenOnly
        windows = torch.tensor([[[1.,0.],[0.,1.]], [[0.,1.],[1.,0.]]])
        weight = torch.tensor([[1.,0.,0.,2.]])
        model = TokenOnly(5, channels=3).eval()
        ids = torch.tensor([[1,3],[2,3]])
        with torch.no_grad():
            print("v1 last-position difference:", (model(ids)[0,-1]-model(ids)[1,-1]).abs().max().item())
        print("windows:", windows, "pooled:", windows.mean(1))
        ''',
        task="تابع `window_readout(x, weight)` را بنویسید: `x` شکل `(B,T,C)` و `weight` شکل `(O,T*C)` دارد؛ خروجی باید `(B,O)` و بدون Bias باشد. فقط محورهای زمان و ویژگی را صاف کنید.",
        starter="def window_readout(x, weight):\n    # TODO\n    return None",
        checks='''
        result = window_readout(windows, weight)
        if result is None: return False
        torch.testing.assert_close(result, torch.tensor([[3.],[0.]]))
        other = torch.arange(24.).reshape(2,3,4)
        w = torch.arange(24.).reshape(2,12)/10
        expected = torch.stack([torch.stack([(sample.reshape(-1)*row).sum() for row in w]) for sample in other])
        torch.testing.assert_close(window_readout(other,w), expected)
        assert window_readout(other,w).shape == (2,2)
        return True
        ''',
        solution="def window_readout(x, weight):\n    return x.flatten(1) @ weight.T",
        vary="فقط جای دو موقعیت را عوض کنید؛ وزن و مجموعهٔ بردارها ثابت بمانند. چرا خوانش پنجره‌ای تغییر می‌کند ولی میانگین نه؟",
        vary_code="print('original:', windows[0].flatten() @ weight[0])\nprint('reversed:', windows[0].flip(0).flatten() @ weight[0])\nprint('same mean:', torch.equal(windows[0].mean(0), windows[0].flip(0).mean(0)))",
        debug="نسخهٔ خراب ترتیب را پیش از خوانش با `mean` حذف کرده است. تابع `ordered_features(x)` را اصلاح کنید تا `(B,T*C)` بدهد؛ با عوض‌کردن وزن، اطلاعات حذف‌شده برنمی‌گردد.",
        bug_code="wrong_features = windows.mean(1)\nprint('different windows, identical features:', torch.equal(wrong_features[0], wrong_features[1]))",
        fix="def ordered_features(x):\n    # TODO\n    return None",
        fix_checks="result = ordered_features(windows)\nif result is None: return False\nassert result.shape == (2,4)\nassert not torch.equal(result[0],result[1])\nassert torch.equal(ordered_features(torch.arange(24).reshape(2,3,4)),torch.arange(24).reshape(2,12))\nreturn True",
        fix_solution="def ordered_features(x):\n    return x.flatten(1)",
        connection="`TokenOnly` واقعی در `mini_gpt/stages/v1.py` هیچ مسیر بین موقعیت‌ها ندارد. خوانش پنجره‌ای این تمرین یک آزمایش کوچک است، نه جایگزین معماری `MiniGPT`؛ توجه در مرحلهٔ بعد این محدودیت را به روش دیگری برطرف می‌کند.",
        takeaway="چه اطلاعاتی از گذشته باید در ساختن خروجیِ آخر نقش داشته باشد؟ چرا نمی‌توان محدودیت v1 را به همهٔ MLPها نسبت داد؟",
    ),
    "26b-sequence-memory": _lab(
        title="اثر یک ورودی پس از چند بازنویسی حافظه",
        goal="حالت بازگشتی را بسازید و ماندگاری یک تغییر کوچک را اندازه بگیرید.",
        prerequisite="حلقهٔ Python و ضرب یک ضریب در حالت قبلی کافی است؛ این مدل خطی، LSTM نیست.",
        predict="در ورودی `[1,0,0,0]` با `factor=0.5` کدام گام بیشترین اثر عدد ۱ را دارد؟ با انتقال ۱ به انتها چه می‌شود؟",
        setup="sequence = [1.,0.,0.,0.]\nprint('input:', sequence, 'retention:', 0.5)",
        task="تابع `recurrent_states(sequence, factor, initial=0.0)` را بنویسید. در هر گام `h=factor*h+x` و خروجی فهرست همهٔ حالت‌ها باشد؛ `initial` فقط پیش از حلقه استفاده شود.",
        starter="def recurrent_states(sequence, factor, initial=0.0):\n    # TODO\n    return None",
        checks="result = recurrent_states(sequence,0.5)\nif result is None: return False\nassert result == [1.,0.5,0.25,0.125]\nassert recurrent_states([0.,0.,0.,1.],0.5)[-1] == 1.\nassert recurrent_states([2.,-1.],2.,initial=3.) == [8.,15.]\nassert recurrent_states([],0.5) == []\nreturn True",
        solution="def recurrent_states(sequence, factor, initial=0.0):\n    h = initial\n    result = []\n    for value in sequence:\n        h = factor*h + value\n        result.append(h)\n    return result",
        vary="فقط `factor` را میان 0.5، 1 و 1.5 تغییر دهید؛ طول ۲۰ و تغییر حالت آغازین ثابت‌اند. این آزمایش دربارهٔ انتقال اثر است، نه کیفیت فهم متن.",
        vary_code="for factor in (0.5,1.,1.5):\n    a,b = 0.,1.\n    for _ in range(20):\n        a,b = factor*a, factor*b\n    print(factor, 'initial-state difference after 20 steps:', b-a)",
        debug="در کد خراب، `h` هر بار داخل حلقه صفر می‌شود. تابع `remember(sequence, factor)` را اصلاح کنید؛ خروجی همهٔ حالت‌هاست و حالت آغازین صفر است.",
        bug_code="wrong = []\nfor value in sequence:\n    h = 0.\n    h = 0.5*h + value\n    wrong.append(h)\nprint('lost memory:', wrong)",
        fix="def remember(sequence, factor):\n    # TODO\n    return None",
        fix_checks="result = remember(sequence,0.5)\nif result is None: return False\nassert result == [1.,0.5,0.25,0.125]\nassert remember([2.,1.,0.],1.) == [2.,3.,3.]\nreturn True",
        fix_solution="def remember(sequence, factor):\n    h = 0.\n    result = []\n    for value in sequence:\n        h = factor*h + value\n        result.append(h)\n    return result",
        connection="`MiniGPT` حالت RNN حمل نمی‌کند. در `mini_gpt/attention.py` هر Query از Valueهای موقعیت‌های مجاز ترکیب می‌سازد؛ این مقایسه علت انتخاب یک مسیر مستقیم‌تر به گذشته را روشن می‌کند.",
        takeaway="در این مثال اثر ورودی قدیمی از چه مسیری می‌گذرد؟ Attention چه مسیر متفاوتی می‌سازد و در عوض چه جدولی را نگه می‌دارد؟",
    ),
    "27-attention-why": _lab(
        title="یک منبع اطلاعات، دو درخواست متفاوت",
        goal="ترکیب وزن‌دار را خودتان بسازید و آن را از میانگین ثابت جدا کنید.",
        prerequisite="جمع و ضرب بردار و معنای محور منبع و ویژگی را مرور کنید.",
        predict="برای Valueهای `[10,0]` و `[0,20]`، درخواست اول وزن `[1,0]` و درخواست دوم `[0.25,0.75]` دارد. هر خروجی چند ویژگی دارد؟",
        setup="values = torch.tensor([[10.,0.],[0.,20.]])\nrequests = torch.tensor([[1.,0.],[0.25,0.75]])\nprint('values:',values,'request weights:',requests)",
        task="تابع `mix_sources(weights, values)` را بنویسید. `weights` شکل `(Q,S)`، `values` شکل `(S,C)` و خروجی شکل `(Q,C)` دارد. هر Query باید ترکیب خودش را بگیرد؛ اینجا وزن‌ها از قبل داده شده‌اند.",
        starter="def mix_sources(weights, values):\n    # TODO\n    return None",
        checks="result = mix_sources(requests,values)\nif result is None: return False\ntorch.testing.assert_close(result,torch.tensor([[10.,0.],[2.5,15.]]))\nv = torch.tensor([[1.,2.,3.],[4.,5.,6.],[-2.,0.,2.]])\nw = torch.tensor([[0.,0.,1.],[0.5,0.5,0.]])\ntorch.testing.assert_close(mix_sources(w,v),torch.stack((v[2],(v[0]+v[1])/2)))\nreturn True",
        solution="def mix_sources(weights, values):\n    return weights @ values",
        vary="فقط سهم منبع اول را از صفر تا یک تغییر دهید و سهم دوم را مکمل آن بگذارید. مسیر خروجی میان دو بردار چگونه است؟",
        vary_code="for alpha in (0.,0.25,0.5,0.75,1.):\n    print(alpha, alpha*values[0]+(1-alpha)*values[1])",
        debug="کد خراب برای همهٔ درخواست‌ها میانگین یکسان می‌دهد. تابع `request_outputs(weights, values)` را طوری اصلاح کنید که واقعاً `weights` را مصرف کند.",
        bug_code="wrong = values.mean(0).expand(requests.shape[0],-1)\nprint('request ignored:',wrong)",
        fix="def request_outputs(weights, values):\n    # TODO\n    return None",
        fix_checks="result = request_outputs(requests,values)\nif result is None: return False\ntorch.testing.assert_close(result,torch.tensor([[10.,0.],[2.5,15.]]))\ntorch.testing.assert_close(request_outputs(torch.eye(2),values),values)\nreturn True",
        fix_solution="def request_outputs(weights, values):\n    return weights @ values",
        connection="این جمع همان `weights @ v` در توجه پروژه است. هنوز خود Attention را کامل نساخته‌ایم: در `MiniGPT` وزن‌ها نیز از ورودی، به کمک Query و Key، محاسبه می‌شوند.",
        takeaway="کدام قسمت این آزمایش مشکل میانگین ثابت را حل کرد و کدام قسمت هنوز دستی تعیین شده است؟",
    ),
    "28-qkv": _lab(
        title="معیار جست‌وجو را از محتوای پاسخ جدا کنید",
        goal="سه Projection مستقل را با قرارداد وزن PyTorch بازسازی کنید.",
        prerequisite="Linear، ضرب ماتریس، Bias و شکل `(B,T,C)` را بشناسید.",
        predict="اگر فقط وزن Value عوض شود، آیا Query و Key هم باید تغییر کنند؟ برابرشدن Weightهای Query و Key بدون برابرشدن Biasها کافی است؟",
        setup='''
        from torch import nn
        x = torch.tensor([[[2.,1.,3.],[1.,0.,-1.]]])
        query, key, value = [nn.Linear(3,2) for _ in range(3)]
        print("input:",x)
        print("weight/bias:",query.weight.shape,query.bias.shape)
        ''',
        task="تابع `project(x, weight, bias)` را بدون صداکردن Linear یا `F.linear` بنویسید. وزن شکل `(D,C)` دارد و Bias شکل `(D,)`؛ محورهای پیشین `x` باید حفظ شوند.",
        starter="def project(x, weight, bias):\n    # TODO\n    return None",
        checks="result = project(x,query.weight,query.bias)\nif result is None: return False\ntorch.testing.assert_close(result,query(x))\nw = torch.tensor([[1.,0.,-1.],[0.,2.,1.]])\nb = torch.tensor([0.5,-1.])\ntorch.testing.assert_close(project(x,w,b)[0,0],torch.tensor([-0.5,4.]))\nz = torch.arange(24.).reshape(2,4,3)\ntorch.testing.assert_close(project(z,key.weight,key.bias),key(z))\nreturn True",
        solution="def project(x, weight, bias):\n    return x @ weight.T + bias",
        vary="از لایهٔ Value یک کپی مستقل بگیرید و فقط وزن آن را دو برابر کنید؛ Bias ثابت بماند. اینجا خروجی خود Linear را مشاهده می‌کنیم. `Q` و `K` ثابت می‌مانند؛ چرا خروجی `V` با Bias غیرصفر الزاماً دو برابر نمی‌شود؟",
        vary_code="from copy import deepcopy\nchanged_value = deepcopy(value)\nwith torch.no_grad():\n    q_before,k_before = query(x),key(x)\n    old_v = value(x)\n    changed_value.weight.mul_(2)\n    changed_v = changed_value(x)\n    print('Q/K unchanged:',torch.equal(q_before,query(x)),torch.equal(k_before,key(x)))\n    print('V change:',changed_v-old_v)\n    print('difference from twice the old V:',changed_v-2*old_v)",
        debug="دو Projection زیر Weight یکسان ولی Bias متفاوت دارند. تابع `copy_projection(source, destination)` را اصلاح کنید تا هر دو را داخل `no_grad` کپی کند و `destination` را برگرداند.",
        bug_code="source,destination = nn.Linear(3,2),nn.Linear(3,2)\nwith torch.no_grad():\n    source.bias.fill_(1.)\n    destination.bias.zero_()\n    destination.weight.copy_(source.weight)\nprint('weight-only copy difference:',(source(x)-destination(x)).detach())",
        fix="def copy_projection(source, destination):\n    # TODO\n    return None",
        fix_checks="result = copy_projection(source,destination)\nif result is None: return False\nassert result is destination\ntorch.testing.assert_close(source(x),destination(x))\ntorch.testing.assert_close(source(torch.ones(2,3)),destination(torch.ones(2,3)))\nassert source.weight is not destination.weight\na,b = nn.Linear(2,3),nn.Linear(2,3)\ncopy_projection(a,b)\ntorch.testing.assert_close(a.weight,b.weight)\ntorch.testing.assert_close(a.bias,b.bias)\nreturn True",
        fix_solution="def copy_projection(source, destination):\n    with torch.no_grad():\n        destination.weight.copy_(source.weight)\n        destination.bias.copy_(source.bias)\n    return destination",
        connection="v2 سه Linear مستقل دارد؛ `CausalSelfAttention` نهایی همان سه تبدیل را در `qkv` با خروجی `3C` کنار هم ذخیره می‌کند. یک فراخوانی به معنی یکسان‌بودن وزن سه نقش نیست.",
        takeaway="در این آزمایش کدام Tensor پارامتر ماندگار بود و کدام Tensor نتیجهٔ اعمال پارامتر به ورودی؟",
    ),
    "29-scores": _lab(
        title="نشانی هر خانهٔ جدول مقایسه",
        goal="امتیاز همهٔ جفت‌های Query و Key را با حلقه بسازید و با `matmul` بسنجید.",
        prerequisite="ضرب داخلی و تفاوت محور موقعیت با محور ویژگی را بشناسید.",
        predict="سه Query دوویژگی و چهار Key دوویژگی داریم. جدول چند سطر و چند ستون دارد؟ خانهٔ `[1,2]` دقیقاً کدام دو بردار را مقایسه می‌کند؟",
        setup="q = torch.tensor([[1.,0.],[0.,1.],[1.,2.]])\nk = torch.tensor([[1.,1.],[0.,1.],[2.,-1.],[3.,0.]])\nprint('Q:',q,'K:',k)",
        task="تابع `pair_scores(q, k)` را با حلقه روی Query و Key بنویسید؛ هر خانه مجموع حاصل‌ضرب ویژگی‌هاست. از `q@k.T` در راه‌حل این بخش استفاده نکنید. خروجی Tensor شکل `(Tq,Tk)` باشد.",
        starter="def pair_scores(q, k):\n    # TODO\n    return None",
        checks="result = pair_scores(q,k)\nif result is None: return False\nassert result.shape == (3,4)\ntorch.testing.assert_close(result,q@k.T)\nassert result[1,2].item() == -1.\nfor a,b in ((q[:1],k[:2]),(torch.ones(2,3),torch.arange(12.).reshape(4,3))):\n    torch.testing.assert_close(pair_scores(a,b),a@b.T)\nreturn True",
        solution="def pair_scores(q, k):\n    return torch.stack([torch.stack([(query*key).sum() for key in k]) for query in q])",
        vary="فقط Key سوم را در منفی یک ضرب کنید. پیش‌بینی کنید کدام ستون جدول علامت عوض می‌کند؛ Queryها و بقیهٔ Keyها ثابت‌اند.",
        vary_code="changed_k = k.clone()\nchanged_k[2] *= -1\nprint('score difference:',q@changed_k.T-q@k.T)",
        debug="حذف `transpose` در مثال مربعی گاهی خطا نمی‌دهد. تابع `score_matrix(q, k)` را اصلاح کنید؛ مثال نامربعی نیز باید کار کند.",
        bug_code="square_q = torch.eye(2)\nsquare_k = torch.tensor([[1.,2.],[3.,4.]])\nprint('same shape, wrong meaning:',square_q@square_k)\ntry:\n    print(q@k)\nexcept RuntimeError as error:\n    print('expected incompatible axes:',error)",
        fix="def score_matrix(q, k):\n    # TODO\n    return None",
        fix_checks="result = score_matrix(q,k)\nif result is None: return False\ntorch.testing.assert_close(result,q@k.T)\ntorch.testing.assert_close(score_matrix(square_q,square_k),square_q@square_k.T)\nreturn True",
        fix_solution="def score_matrix(q, k):\n    return q @ k.transpose(-2,-1)",
        connection="`raw_scores` در `mini_gpt/attention.py` همین مقایسه‌هاست؛ در مدل، محورهای Batch و Head جلو این دو محور قرار می‌گیرند. هنوز Softmax و Mask اعمال نشده‌اند.",
        takeaway="چرا موفق‌بودن ضرب دو ماتریس مربعی برای تأیید معنای محورهای Attention کافی نیست؟",
    ),
    "30-scaling": _lab(
        title="وقتی تعداد ویژگی‌ها امتیاز را بزرگ می‌کند",
        goal="مقیاس درست امتیاز را پیاده کنید و ادعای آماری آن را از یک برابری دقیق جدا نگه دارید.",
        prerequisite="ضرب داخلی، Softmax و Standard deviation را از متن درس مرور کنید.",
        predict="اگر پراکندگی امتیاز خام برای `D=64` نزدیک ۸ باشد، تقسیم بر ۸ و تقسیم بر ۶۴ چه تفاوتی دارند؟",
        setup="q = torch.tensor([[1.,2.,3.,4.],[0.,1.,0.,1.]])\nk = torch.tensor([[2.,0.,1.,0.],[1.,1.,1.,1.],[0.,0.,2.,2.]])\nprint('raw scores:',q@k.T)",
        task="تابع `scaled_scores(q, k)` را برای محور آخرِ ویژگی بنویسید. مخرج باید ریشهٔ تعداد ویژگی‌های همان بردار Query باشد؛ تعداد موقعیت‌ها یا `C` کل مدل را به تابع تحمیل نکنید.",
        starter="def scaled_scores(q, k):\n    # TODO\n    return None",
        checks="result = scaled_scores(q,k)\nif result is None: return False\ntorch.testing.assert_close(result,(q@k.T)/2)\na,b = torch.ones(2,3,9),torch.ones(2,5,9)\ntorch.testing.assert_close(scaled_scores(a,b),torch.full((2,3,5),3.))\ntorch.testing.assert_close(scaled_scores(torch.ones(1,1),torch.ones(2,1)),torch.ones(1,2))\nreturn True",
        solution="def scaled_scores(q, k):\n    return (q @ k.transpose(-2,-1)) / math.sqrt(q.shape[-1])",
        vary="فقط `D` را تغییر دهید؛ ۲۰۰۰ جفت مستقل نرمال برای هر اندازه بسازید. این گزارش نمونه‌ای است: انتظار مقدار دقیقاً یک یا روند کاملاً یکنواخت نداریم.",
        vary_code="generator = torch.Generator().manual_seed(31)\nfor D in (4,16,64):\n    a = torch.randn(2000,D,generator=generator)\n    b = torch.randn(2000,D,generator=generator)\n    raw = (a*b).sum(-1)\n    print(D,'raw std:',raw.std().item(),'scaled std:',(raw/math.sqrt(D)).std().item())",
        debug="در توجه چندسر `C=12` و `H=3`، هر بردار چهار ویژگی دارد. کد خراب بر `sqrt(C)` تقسیم می‌کند. تابع `head_scores(q,k)` را از خود Shape اصلاح کنید.",
        bug_code="head_q,head_k = torch.ones(1,3,2,4),torch.ones(1,3,2,4)\nprint('wrong C scaling:',(head_q@head_k.transpose(-2,-1))/math.sqrt(12))",
        fix="def head_scores(q, k):\n    # TODO\n    return None",
        fix_checks="result = head_scores(head_q,head_k)\nif result is None: return False\ntorch.testing.assert_close(result,torch.full((1,3,2,2),2.))\ntorch.testing.assert_close(head_scores(torch.ones(1,2,3,9),torch.ones(1,2,4,9)),torch.full((1,2,3,4),3.))\nreturn True",
        fix_solution="def head_scores(q, k):\n    return (q @ k.transpose(-2,-1)) / math.sqrt(q.shape[-1])",
        connection="`CausalSelfAttention` از `head_dim` استفاده می‌کند، نه `channels`. آزمون‌های دقیق ما خود تقسیم را می‌سنجند؛ آزمایش آماری فقط انگیزهٔ انتخاب آن را نشان می‌دهد.",
        takeaway="کدام نتیجهٔ این دفتر یک قرارداد قطعی کد بود و کدام نتیجه به فرض‌های توزیع تصادفی وابسته بود؟",
    ),
    "31-values": _lab(
        title="از جدول مقایسه تا بردار پاسخ",
        goal="Softmax سطری و ترکیب Valueها را در یک تابع قابل آزمون به هم وصل کنید.",
        prerequisite="امتیاز مقیاس‌شده و جمع وزن‌دار را از دو درس قبل بشناسید.",
        predict="دو Query با امتیازهای متفاوت داریم. اگر فقط Valueها دو برابر شوند، کدام خروجی تابع باید ثابت بماند؟",
        setup="scores = torch.tensor([[1.,0.,-1.],[0.,0.,0.]])\nvalues = torch.tensor([[10.,0.],[0.,20.],[-10.,5.]])\nprint('scores:',scores,'values:',values)",
        task="تابع `attend(scores, values)` یک زوج `(weights, output)` برگرداند. Softmax را بدون `torch.softmax` بسازید: بیشینهٔ هر سطر را کم کنید، `exp` بگیرید و بر مجموع همان سطر تقسیم کنید؛ سپس Valueها را ترکیب کنید.",
        starter="def attend(scores, values):\n    # TODO\n    return None",
        checks="result = attend(scores,values)\nif result is None: return False\nweights,out = result\ntorch.testing.assert_close(weights,scores.softmax(-1))\ntorch.testing.assert_close(out,scores.softmax(-1)@values)\ntorch.testing.assert_close(out[1],values.mean(0))\nlarge = torch.tensor([[1000.,1001.,999.]])\nw,y = attend(large,values)\nassert torch.isfinite(w).all() and torch.isfinite(y).all()\ntorch.testing.assert_close(w,large.softmax(-1))\nreturn True",
        solution="def attend(scores, values):\n    shifted = scores-scores.max(-1,keepdim=True).values\n    exponential = shifted.exp()\n    weights = exponential/exponential.sum(-1,keepdim=True)\n    return weights, weights@values",
        vary="برای جداکردن اثر Value، در این آزمایش وزن‌ها را از قبل تعیین کرده‌ایم؛ این جدول از `scores` محاسبه نشده است. فقط ضریب Value را از یک به دو تغییر دهید و خروجی را مقایسه کنید، نه فقط Shape را.",
        vary_code="fixed_weights = torch.tensor([[0.7,0.2,0.1],[1/3,1/3,1/3]])\nprint('original:',fixed_weights@values)\nprint('doubled values:',fixed_weights@(2*values))\nprint('same weights:',fixed_weights)",
        debug="کد خراب روی محور Query نرمال می‌کند. تابع `key_weights(scores)` را اصلاح کنید تا هر Query توزیع خودش را روی Keyها داشته باشد.",
        bug_code="wrong = scores.softmax(0)\nprint('wrong row sums:',wrong.sum(-1),'column sums:',wrong.sum(0))",
        fix="def key_weights(scores):\n    # TODO\n    return None",
        fix_checks="result = key_weights(scores)\nif result is None: return False\ntorch.testing.assert_close(result.sum(-1),torch.ones(2))\ntorch.testing.assert_close(result,scores.softmax(-1))\nother = torch.tensor([[1.,2.],[0.,0.],[-2.,3.]])\ntorch.testing.assert_close(key_weights(other),other.softmax(-1))\nreturn True",
        fix_solution="def key_weights(scores):\n    return scores.softmax(-1)",
        connection="دو خروجی تابع با `weights` و `weighted_values` در `trace` توجه پروژه متناظرند؛ در این تمرین Dropout نداریم. محاسبه هنوز بدون Mask است و برای آموزش علّی کافی نیست.",
        takeaway="اگر وزن‌ها مجموع یک داشته باشند اما روی محور اشتباه نرمال شده باشند، چه معنایی از Attention از دست می‌رود؟",
    ),
    "32-self": _lab(
        title="نسخهٔ دوم را از قطعه‌های خودش بازسازی کنید",
        goal="مسیر تک‌سر واقعی v2 را مونتاژ و تفاوت وزن Attention با Logits را مشاهده کنید.",
        prerequisite="Embedding، `Q/K/V`، امتیاز مقیاس‌شده و ترکیب Value را بشناسید.",
        predict="با واژگان ۱۲تایی و ورودی چهارموقعیتی، وزن Attention و خروجی مدل چه شکل‌هایی دارند؟ آیا واژهٔ Self یعنی فقط قطر جدول مجاز است؟",
        setup="from mini_gpt.stages.v2 import SingleHead\nmodel = SingleHead(12,channels=6).eval()\nids = torch.tensor([[1,2,3,4]])\nwith torch.no_grad():\n    reference = model(ids)\nprint('logits shape:',reference.shape,'weights shape:',model.last_weights.shape)",
        task="تابع `assemble_v2(model, ids)` را با `embedding`، `query`، `key`، `value` و `head` همین شیء بسازید؛ خود `model(ids)` را در پاسخ صدا نزنید. زوج `(logits, weights)` برگردانید. v2 در این دفتر بدون Mask است.",
        starter="def assemble_v2(model, ids):\n    # TODO\n    return None",
        checks="result = assemble_v2(model,ids)\nif result is None: return False\nfor tokens in (ids,torch.tensor([[4,2,1],[2,2,3]])):\n    logits,weights = assemble_v2(model,tokens)\n    expected = model(tokens)\n    torch.testing.assert_close(logits,expected)\n    torch.testing.assert_close(weights,model.last_weights)\n    assert logits.shape[-1] == 12\n    torch.testing.assert_close(weights.sum(-1),torch.ones_like(weights.sum(-1)))\nreturn True",
        solution="def assemble_v2(model, ids):\n    x = model.embedding(ids)\n    q,k,v = model.query(x),model.key(x),model.value(x)\n    weights = (q@k.transpose(-2,-1)/math.sqrt(q.shape[-1])).softmax(-1)\n    return model.head(weights@v), weights",
        vary="فقط دو Token آینده را عوض کنید؛ همان مدل با همان وزن‌ها را نگه دارید. اختلاف پیشوند، امکان دریافت اطلاعات آینده را نشان می‌دهد نه کیفیت زبان را.",
        vary_code="changed = ids.clone()\nchanged[:,2:] = torch.tensor([9,10])\nwith torch.no_grad():\n    print('prefix change in unmasked v2:',(model(ids)[:,:2]-model(changed)[:,:2]).abs().max().item())",
        debug="پیاده‌سازی خراب، Self را به معنی «فقط خود موقعیت» گرفته است. تابع `self_weights(q,k)` را اصلاح کنید: منبع `Q` و `K` یکی است، اما همهٔ جفت‌ها در این نسخهٔ بدون Mask مجازند.",
        bug_code="wrong_weights = torch.eye(ids.shape[1])[None]\nprint('diagonal-only interpretation:',wrong_weights)",
        fix="def self_weights(q, k):\n    # TODO\n    return None",
        fix_checks="q,k = torch.zeros(1,3,2),torch.zeros(1,3,2)\nresult = self_weights(q,k)\nif result is None: return False\ntorch.testing.assert_close(result,torch.full((1,3,3),1/3))\nq,k = torch.ones(1,2,4),torch.arange(8.).reshape(1,2,4)\ntorch.testing.assert_close(self_weights(q,k),(q@k.transpose(-2,-1)/2).softmax(-1))\nreturn True",
        fix_solution="def self_weights(q, k):\n    return (q@k.transpose(-2,-1)/math.sqrt(q.shape[-1])).softmax(-1)",
        connection="تمام پارامترها از `SingleHead` واقعی گرفته شدند؛ کپی دیگری از مدل تولیدی نساختیم. `last_weights` ابزار مشاهده است، در حالی که `forward` این کلاس Logits را برمی‌گرداند.",
        takeaway="چرا Self-Attention به‌تنهایی هیچ تضمینی دربارهٔ ندیدن آینده نمی‌دهد؟",
    ),
    "33-mask": _lab(
        title="پاسخ آینده را از جدول خارج کنید",
        goal="Mask علّی را پیش از Softmax اعمال کنید و قطر و مجموع سطرها را بسنجید.",
        prerequisite="محورهای Query/Key و Softmax سطری را بشناسید.",
        predict="در جدول سه‌موقعیتی، سطر صفر چند Key مجاز دارد؟ اگر امتیاز آینده را صفر کنیم، `exp` آن صفر می‌شود؟",
        setup="scores = torch.tensor([[1.,2.,3.],[4.,2.,0.],[-1.,0.,1.]])\nprint('unmasked weights:',scores.softmax(-1))",
        task="تابع `causal_weights(scores)` برای Tensor مربعی `(...,T,T)` بنویسید. قطر و پایین آن مجازند؛ خانه‌های دیگر پیش از Softmax به `-inf` بروند. خروجی وزن‌ها باشد و ورودی را درجا تغییر ندهید.",
        starter="def causal_weights(scores):\n    # TODO\n    return None",
        checks="original = scores.clone()\nresult = causal_weights(scores)\nif result is None: return False\ntorch.testing.assert_close(result[0],torch.tensor([1.,0.,0.]))\nassert torch.count_nonzero(result.triu(1)) == 0\ntorch.testing.assert_close(result.sum(-1),torch.ones(3))\nassert torch.equal(scores,original)\nfor T in (1,4):\n    s = torch.zeros(2,3,T,T)\n    w = causal_weights(s)\n    torch.testing.assert_close(w.sum(-1),torch.ones(2,3,T))\n    torch.testing.assert_close(w[..., -1,:],torch.full((2,3,T),1/T))\nreturn True",
        solution="def causal_weights(scores):\n    T = scores.shape[-1]\n    allowed = torch.ones(T,T,dtype=torch.bool,device=scores.device).tril()\n    return scores.masked_fill(~allowed,float('-inf')).softmax(-1)",
        vary="تابع آمادهٔ PyTorch با `is_causal=True` محدودیت علّی را درون خودش اعمال می‌کند. `Q` و `K` را ثابت نگه دارید و فقط Value موقعیت آخر را تغییر دهید. خروجی دو موقعیت اول باید ثابت بماند؛ چرا موقعیت آخر می‌تواند تغییر کند؟ اینجا خروجی Attention را می‌بینیم، نه خود جدول وزن‌ها را.",
        vary_code="from torch.nn import functional as F\nallowed = torch.tensor([[True,False,False],[True,True,False],[True,True,True]])\nq,k = torch.eye(3),torch.eye(3)\nv = torch.tensor([[1.,2.],[3.,4.],[5.,6.]])\nchanged_v = v.clone()\nchanged_v[-1] += 1000\nbefore = F.scaled_dot_product_attention(q,k,v,is_causal=True,dropout_p=0.)\nafter = F.scaled_dot_product_attention(q,k,changed_v,is_causal=True,dropout_p=0.)\nprint('allowed keys per query:',allowed.sum(-1))\nprint('output change per query:',(after-before).abs().amax(-1))\ntorch.testing.assert_close(before[:2],after[:2])",
        debug="نسخهٔ خراب امتیاز ممنوع را صفر می‌کند. تابع `repair_mask(scores)` را اصلاح کنید؛ سطر بدون Key مجاز نسازید.",
        bug_code="wrong = scores.masked_fill(~allowed,0.).softmax(-1)\nprint('future mass in first row:',wrong[0,1:].sum().item())\nstrict = torch.ones(3,3,dtype=torch.bool).tril(-1)\nprint('empty first row is finite:',torch.isfinite(scores.masked_fill(~strict,float('-inf')).softmax(-1)[0]).all().item())",
        fix="def repair_mask(scores):\n    # TODO\n    return None",
        fix_checks="result = repair_mask(scores)\nif result is None: return False\nassert torch.isfinite(result).all()\nassert result[0,0].item() == 1.\nassert torch.count_nonzero(result.triu(1)) == 0\nexpected = scores.masked_fill(~torch.ones(3,3,dtype=torch.bool).tril(),float('-inf')).softmax(-1)\ntorch.testing.assert_close(result,expected)\ntorch.testing.assert_close(repair_mask(torch.zeros(2,2)),torch.tensor([[1.,0.],[0.5,0.5]]))\ntorch.testing.assert_close(repair_mask(torch.zeros(1,1)),torch.ones(1,1))\nreturn True",
        fix_solution="def repair_mask(scores):\n    allowed = torch.ones(scores.shape[-2:],dtype=torch.bool,device=scores.device).tril()\n    return scores.masked_fill(~allowed,float('-inf')).softmax(-1)",
        connection="v3 همین محدودیت را به v2 اضافه می‌کند؛ `CausalSelfAttention` نهایی Mask را به‌صورت Buffer نگه می‌دارد. وجود Token آینده در Batch با مجازبودن دسترسی به آن یکی نیست.",
        takeaway="چرا قطر جدول مجاز است ولی ستون بعد از آن می‌تواند پاسخ هدف فعلی را لو بدهد؟",
    ),
    "34-causal-test": _lab(
        title="آزمونی که نشت آینده را می‌گیرد",
        goal="یک آزمون رفتاری برای تغییر پیشوند بسازید که اطلاعات را از تصادف Dropout جدا کند.",
        prerequisite="Mask علّی، `eval` و تفاوت آن با `no_grad` را بشناسید.",
        predict="دو ورودی تا موقعیت دوم یکسان‌اند. برای خروجی‌های همین پیشوند، چه مقایسه‌ای باید در یک مدل علّی برقرار باشد؟",
        setup='''
        from mini_gpt.attention import CausalSelfAttention
        from mini_gpt.config import ModelConfig
        attention = CausalSelfAttention(ModelConfig(8,6,4,1,1,0.)).eval()
        # A controlled fixture: uniform attention and identity Value/output.
        with torch.no_grad():
            attention.qkv.weight.zero_(); attention.qkv.bias.zero_()
            attention.qkv.weight[8:12].copy_(torch.eye(4))
            attention.output.weight.copy_(torch.eye(4)); attention.output.bias.zero_()
        x = torch.arange(16.).reshape(1,4,4)
        changed = x.clone(); changed[:,2:] += 10
        print("same prefix:",torch.equal(x[:,:2],changed[:,:2]))
        ''',
        task="تابع `prefix_change(attention, a, b, prefix, causal)` بیشینهٔ اختلاف مطلق خروجی دو ورودی را فقط در `:prefix` برگرداند؛ از همان شیء، حالت `eval` و `no_grad` استفاده کنید. خروجی یک `float` باشد.",
        starter="def prefix_change(attention, a, b, prefix, causal):\n    # TODO\n    return None",
        checks="result = prefix_change(attention,x,changed,2,True)\nif result is None: return False\nassert result < 1e-7\nassert abs(prefix_change(attention,x,changed,2,False)-5.) < 1e-6\nassert prefix_change(attention,x,x,4,False) == 0.\nother = x.clone(); other[:,3:] += 8\nassert prefix_change(attention,x,other,3,True) < 1e-7\nreturn True",
        solution="def prefix_change(attention, a, b, prefix, causal):\n    attention.eval()\n    with torch.no_grad():\n        difference = attention(a,causal=causal)[:,:prefix]-attention(b,causal=causal)[:,:prefix]\n    return difference.abs().max().item()",
        vary="فقط پرچم `causal` را تغییر دهید. این نمونهٔ کنترل‌شده عمداً `Q/K` صفر دارد؛ بدون Mask اثر آینده دقیقاً قابل محاسبه است و به یک Seed خوش‌شانس تکیه نمی‌کند.",
        vary_code="with torch.no_grad():\n    for causal in (False,True):\n        difference = attention(x,causal=causal)[:,:2]-attention(changed,causal=causal)[:,:2]\n        print(causal,difference.abs().max().item())",
        debug="تابع خراب کل دنباله را مقایسه می‌کند؛ تغییر خروجیِ موقعیت‌های تغییرکرده نشت آینده نیست. تابع `prefix_difference(a,b,prefix)` را برای دو Tensor خروجی اصلاح کنید.",
        bug_code="a = torch.zeros(1,4,2)\nb = a.clone(); b[:,2:] = 7.\nprint('wrong whole-sequence test:',(a-b).abs().max().item())",
        fix="def prefix_difference(a, b, prefix):\n    # TODO\n    return None",
        fix_checks="result = prefix_difference(a,b,2)\nif result is None: return False\nassert result == 0.\nassert prefix_difference(a,b,3) == 7.\nc = b.clone(); c[:,0,0] = -2.\nassert prefix_difference(a,c,1) == 2.\nreturn True",
        fix_solution="def prefix_difference(a, b, prefix):\n    return (a[:,:prefix]-b[:,:prefix]).abs().max().item()",
        connection="آزمون `test_causal_prefix_invariance` در `tests/test_model.py` همین قرارداد را روی `MiniGPT` کامل می‌سنجد. اینجا از Attention واقعی با وزن‌های کنترل‌شده شروع کردیم؛ مثلثی‌بودن تصویر به‌تنهایی کافی نیست.",
        takeaway="اگر دو اجرای یک ورودی در حالت `train` متفاوت باشند، قبل از نسبت‌دادن اختلاف به نشت آینده چه عامل دیگری را باید حذف کنید؟",
    ),
    "35-split-heads": _lab(
        title="هیچ عددی نباید به Head اشتباه برود",
        goal="تقسیم ویژگی‌ها را با نشانی عناصر، نه فقط Shape، تأیید کنید.",
        prerequisite="`reshape` و `transpose` و رابطهٔ `C=H*D` را مرور کنید.",
        predict="در `x` شکل `(2,5,12)` با `H=3`، عنصر `x[1,3,9]` بعد از تقسیم در کدام Head و کدام ویژگی آن است؟",
        setup="from mini_gpt.config import ModelConfig\nfrom mini_gpt.attention import CausalSelfAttention\nx = torch.arange(120.).reshape(2,5,12)\nprint('tracked value:',x[1,3,9].item())",
        task="تابع `split_heads(x, heads)` را بنویسید: `(B,T,C)` به `(B,H,T,D)`. اگر `C` بر `H` بخش‌پذیر نیست یا `H` مثبت نیست، `ValueError` بدهید. داده را حذف یا با صفر پر نکنید.",
        starter="def split_heads(x, heads):\n    # TODO\n    return None",
        checks="result = split_heads(x,3)\nif result is None: return False\nassert result.shape == (2,3,5,4)\nassert result[1,2,3,1] == x[1,3,9]\nfor H in (1,2,4):\n    out = split_heads(x,H); D = 12//H\n    for h in range(H):\n        assert torch.equal(out[:,h],x[:,:,h*D:(h+1)*D])\nfor invalid in (0,-1,5):\n    try: split_heads(x,invalid)\n    except ValueError: pass\n    else: raise AssertionError('reject invalid C/H')\nattention = CausalSelfAttention(ModelConfig(12,8,12,3,1,0.)).eval()\ntrace = {}; attention(x,trace=trace)\nq = attention.qkv(x).chunk(3,-1)[0]\ntorch.testing.assert_close(split_heads(q,3),trace['q'])\nreturn True",
        solution="def split_heads(x, heads):\n    B,T,C = x.shape\n    if heads <= 0 or C % heads: raise ValueError('invalid head count')\n    return x.reshape(B,T,heads,C//heads).transpose(1,2)",
        vary="فقط `H` را میان ۱، ۳ و ۴ تغییر دهید و `C=12` را ثابت نگه دارید. `D` و تعداد جدول‌های Attention چه می‌شوند؟",
        vary_code="for H in (1,3,4):\n    config = ModelConfig(12,8,12,H,1,0.)\n    module = CausalSelfAttention(config)\n    print('H,D,parameters:',H,12//H,sum(p.numel() for p in module.parameters()))",
        debug="`reshape` مستقیم به `(B,H,T,D)` Shape درست ولی نشانی اشتباه می‌سازد. تابع `repair_split(x, heads)` را اصلاح کنید؛ ورودی‌های این بخش تقسیم‌پذیرند.",
        bug_code="wrong = x.reshape(2,3,5,4)\nprint('wrong value:',wrong[1,2,3,1].item(),'expected:',x[1,3,9].item())",
        fix="def repair_split(x, heads):\n    # TODO\n    return None",
        fix_checks="result = repair_split(x,3)\nif result is None: return False\nassert torch.equal(result[:,1],x[:,:,4:8])\ny = torch.arange(48.).reshape(1,4,12)\nassert torch.equal(repair_split(y,2)[:,1],y[:,:,6:])\nreturn True",
        fix_solution="def repair_split(x, heads):\n    B,T,C = x.shape\n    return x.reshape(B,T,heads,C//heads).transpose(1,2)",
        connection="تابع شما با `q` ثبت‌شده در `trace` واقعی `CausalSelfAttention` مقایسه شد. تقسیم پس از Projection انجام می‌شود؛ هر Head همهٔ موقعیت‌های مجاز را می‌بیند، نه یک قطعهٔ متن جدا.",
        takeaway="کدام assertion می‌توانست خطایی را بگیرد که آزمون Shape از آن عبور می‌کرد؟",
    ),
    "36-merge-heads": _lab(
        title="چسباندن خروجی Headها و شمارش جدول توجه",
        goal="خروجی واقعی Headها را ادغام کنید و Projection نهایی را با ماژول پروژه تطبیق دهید.",
        prerequisite="تقسیم Head و شکل `weights @ V` را بشناسید.",
        predict="اگر `attended` شکل `(2,3,5,4)` دارد، خروجی ادغام چه شکلی است؟ چرا `reshape` مستقیم ممکن است ترتیب موقعیت‌ها را مخلوط کند؟",
        setup="from mini_gpt.config import ModelConfig\nfrom mini_gpt.attention import CausalSelfAttention\nattention = CausalSelfAttention(ModelConfig(12,8,12,3,1,0.)).eval()\nx = torch.randn(2,5,12)\ntrace = {}\nwith torch.no_grad():\n    output = attention(x,trace=trace)\nattended = trace['weighted_values']\nprint('per-head output:',attended.shape)",
        task="تابع `merge_heads(attended)` را بنویسید: `(B,H,T,D)` به `(B,T,H*D)`. هر زمان باید ویژگی‌های Headهای همان زمان را کنار هم داشته باشد.",
        starter="def merge_heads(attended):\n    # TODO\n    return None",
        checks="result = merge_heads(attended)\nif result is None: return False\ntorch.testing.assert_close(attention.output(result),output)\nfor B,H,T,D in ((1,2,3,4),(2,3,2,1)):\n    a = torch.arange(B*H*T*D).reshape(B,H,T,D)\n    merged = merge_heads(a)\n    assert merged.shape == (B,T,H*D)\n    for h in range(H):\n        assert torch.equal(merged[:,:,h*D:(h+1)*D],a[:,h])\nreturn True",
        solution="def merge_heads(attended):\n    B,H,T,D = attended.shape\n    return attended.transpose(1,2).contiguous().view(B,T,H*D)",
        vary="فقط `T` را دو برابر کنید و `B=2` و `H=3` و `float32` را ثابت بگذارید. فقط حافظهٔ یک جدول وزن را حساب می‌کنیم، نه کل حافظهٔ مدل.",
        vary_code="for T in (16,32,64):\n    elements = 2*3*T*T\n    print('T, elements, KiB:',T,elements,elements*4/1024)",
        debug="`contiguous` نمی‌تواند محور معنایی اشتباه را اصلاح کند. تابع `repair_merge(a)` را اصلاح کنید؛ دادهٔ `arange` کمک می‌کند محل اشتباه را ببینید.",
        bug_code="marker = torch.arange(24).reshape(1,2,3,4)\nprint('wrong first position:',marker.contiguous().view(1,3,8)[0,0])\nprint('two correct head pieces:',marker[0,0,0],marker[0,1,0])",
        fix="def repair_merge(a):\n    # TODO\n    return None",
        fix_checks="result = repair_merge(marker)\nif result is None: return False\nassert torch.equal(result[0,0],torch.cat((marker[0,0,0],marker[0,1,0])))\na = torch.arange(60).reshape(2,3,5,2)\nassert torch.equal(repair_merge(a)[:,:,2:4],a[:,1])\nreturn True",
        fix_solution="def repair_merge(a):\n    B,H,T,D = a.shape\n    return a.transpose(1,2).reshape(B,T,H*D)",
        connection="مقایسه با `attention.output` روی همان وزن‌ها انجام شد؛ Dropout صفر است. این بخش انتهای `CausalSelfAttention` مشترک میان v4 و `MiniGPT` نهایی است.",
        takeaway="چرا دوبرابرکردن Batch و دوبرابرکردن `T` اثر یکسانی بر حافظهٔ جدول وزن ندارند؟",
    ),
    "37-ffn": _lab(
        title="وزن‌های مشترک، پردازش جداگانهٔ هر موقعیت",
        goal="FFN واقعی را از وزن‌هایش بازسازی کنید و استقلال موقعیت‌ها را بسنجید.",
        prerequisite="دو Linear با Activation میان آن‌ها و محور آخر ویژگی را بشناسید.",
        predict="اگر دو موقعیت ورودی یکسان باشند، FFN با وزن مشترک چه خروجی‌هایی می‌دهد؟ تغییر موقعیت سوم به آن دو راهی دارد؟",
        setup="from torch.nn import functional as F\nfrom mini_gpt.config import ModelConfig\nfrom mini_gpt.transformer import FeedForward\nffn = FeedForward(ModelConfig(12,8,4,1,1,0.)).eval()\nx = torch.randn(2,3,4)\nx[:,1] = x[:,0]\nprint('matching positions:',torch.equal(x[:,0],x[:,1]))",
        task="تابع `manual_ffn(ffn, x)` را با وزن و Bias لایه‌های ۰ و ۲ در `ffn.layers` بنویسید. بین دو تبدیل `F.gelu` به کار ببرید؛ خود `ffn(x)` یا Sequential کامل را صدا نزنید. Dropout این آزمایش صفر است.",
        starter="def manual_ffn(ffn, x):\n    # TODO\n    return None",
        checks="result = manual_ffn(ffn,x)\nif result is None: return False\ntorch.testing.assert_close(result,ffn(x))\ntorch.testing.assert_close(result[:,0],result[:,1])\nchanged = x.clone(); changed[:,2] += 20\ntorch.testing.assert_close(manual_ffn(ffn,changed)[:,:2],result[:,:2])\nother = torch.randn(1,5,4)\ntorch.testing.assert_close(manual_ffn(ffn,other),ffn(other))\nreturn True",
        solution="def manual_ffn(ffn, x):\n    first,last = ffn.layers[0],ffn.layers[2]\n    hidden = x@first.weight.T + first.bias\n    return F.gelu(hidden)@last.weight.T + last.bias",
        vary="فقط موقعیت آخر را به اندازهٔ ۱۰ افزایش دهید. اختلاف خروجی هر موقعیت را جدا چاپ کنید؛ صفرهای سایر موقعیت‌ها مهم‌تر از مقدار عددی اختلاف آخرند.",
        vary_code="changed = x.clone(); changed[:,-1] += 10\nwith torch.no_grad():\n    print('per-position change:',(ffn(changed)-ffn(x)).abs().amax(-1))",
        debug="نسخهٔ خراب قبل از FFN میانگین زمان را می‌گیرد و به همهٔ موقعیت‌ها می‌دهد. تابع `local_ffn(ffn,x)` را اصلاح کنید؛ در این بخش می‌توانید خود `ffn` را فراخوانی کنید.",
        bug_code="with torch.no_grad():\n    wrong = ffn(x.mean(1,keepdim=True)).expand_as(x)\nprint('wrong: all positions identical:',torch.equal(wrong[:,0],wrong[:,2]))",
        fix="def local_ffn(ffn, x):\n    # TODO\n    return None",
        fix_checks="result = local_ffn(ffn,x)\nif result is None: return False\ntorch.testing.assert_close(result,ffn(x))\nchanged = x.clone(); changed[:,2] -= 100\ntorch.testing.assert_close(local_ffn(ffn,changed)[:,:2],result[:,:2])\nreturn True",
        fix_solution="def local_ffn(ffn, x):\n    return ffn(x)",
        connection="این همان `FeedForward` در `mini_gpt/transformer.py` است. FFN اطلاعات همسایه را مستقیماً نمی‌خواند؛ اطلاعات گذشته پیش‌تر از راه Attention وارد نمایش آن موقعیت شده است.",
        takeaway="اگر FFN را تنها نگه داریم، تغییر گذشته از کدام مسیر می‌تواند به Token فعلی برسد؟ چرا وزن مشترک با ورودی مشترک یکی نیست؟",
    ),
    "38-residual": _lab(
        title="یک راه مستقیم برای مقدار و مشتق",
        goal="اثر مسیر جمع را در خروجی و Gradient جداگانه مشاهده کنید.",
        prerequisite="جمع عضو‌به‌عضو، `requires_grad` و `backward` را بشناسید.",
        predict="اگر زیرلایه اصلاح صفر بسازد، `y=x+f(x)` چه می‌شود؟ برای `f(x)=2x` مشتق چند است و برای `f(x)=-x` چه؟",
        setup="x = torch.tensor([2.,-1.,3.],requires_grad=True)\nprint('input preserved by zero update:',x+torch.zeros_like(x))",
        task="تابع `residual_update(x, scale)` را برای `f(x)=scale*x` بنویسید. Tensor خروجی باید هم مقدار `x` را نگه دارد و هم مسیر مشتق مستقیم آن را؛ از `detach` یا ساخت Tensor تازه از عددها استفاده نکنید.",
        starter="def residual_update(x, scale):\n    # TODO\n    return None",
        checks="result = residual_update(x,2.)\nif result is None: return False\ntorch.testing.assert_close(result,3*x)\ngrad = torch.autograd.grad(result.sum(),x)[0]\ntorch.testing.assert_close(grad,torch.full_like(x,3.))\nfor scale in (0.,-1.,0.5):\n    z = torch.tensor([1.,4.],requires_grad=True)\n    y = residual_update(z,scale)\n    torch.testing.assert_close(y,(1+scale)*z)\n    torch.testing.assert_close(torch.autograd.grad(y.sum(),z)[0],torch.full_like(z,1+scale))\nreturn True",
        solution="def residual_update(x, scale):\n    return x + scale*x",
        vary="برای مشاهدهٔ مسیر مستقیم در بلوک واقعی، همهٔ پارامترهای آن را موقتاً صفر می‌کنیم؛ جزئیات داخل بلوک را در درس‌های بعد باز می‌کنیم. فقط گزینهٔ `residual` را تغییر دهید. ورودی و وزن‌ها ثابت‌اند. نتیجهٔ این حالت کنترل‌شده را با تضمین غیرصفرماندن Gradient در هر مدل اشتباه نگیرید.",
        vary_code="from mini_gpt.config import ModelConfig\nfrom mini_gpt.transformer import TransformerBlock\nblock = TransformerBlock(ModelConfig(8,4,4,1,1,0.)).eval()\nwith torch.no_grad():\n    for parameter in block.parameters():\n        parameter.zero_()\nfor enabled in (False,True):\n    z = torch.arange(8.).reshape(1,2,4).requires_grad_()\n    y = block(z,residual=enabled)\n    gradient = torch.autograd.grad(y.sum(),z)[0]\n    print('residual, output, input gradient:',enabled,y.detach(),gradient)",
        debug="کد خراب `x.detach` را در میان‌بر می‌گذارد. مقدار خروجی همان است، ولی یک سهم مشتق حذف می‌شود. تابع `intact_skip(x, update)` را اصلاح کنید؛ `update` یک Tensor وابسته به `x` است.",
        bug_code="z = torch.tensor(4.,requires_grad=True)\nwrong = z.detach()+2*z\nwrong.backward()\nprint('same output, missing skip gradient:',wrong.item(),z.grad.item())",
        fix="def intact_skip(x, update):\n    # TODO\n    return None",
        fix_checks="z = torch.tensor([2.,3.],requires_grad=True)\nresult = intact_skip(z,2*z)\nif result is None: return False\ntorch.testing.assert_close(torch.autograd.grad(result.sum(),z)[0],torch.full_like(z,3.))\nz = torch.tensor(2.,requires_grad=True)\nassert torch.autograd.grad(intact_skip(z,0*z),z)[0].item() == 1.\nreturn True",
        fix_solution="def intact_skip(x, update):\n    return x + update",
        connection="`TransformerBlock` دو بار جمع مستقیم دارد. در API واقعی، `residual=False` هر دو جمع را حذف می‌کند؛ این با `detach`کردن میان‌بر یا کم‌کردن `x` از خروجی نهایی یکسان نیست.",
        takeaway="چرا آزمون فقط مقدار خروجی، خطای `detach` در مسیر مستقیم را پیدا نمی‌کند؟",
    ),
    "39-layernorm": _lab(
        title="مرکز و پراکندگی کدام بردار؟",
        goal="LayerNorm را روی محور درست و با Gamma/Beta واقعی بازسازی کنید.",
        prerequisite="میانگین، واریانس با `correction=0` و Broadcasting را مرور کنید.",
        predict="بردارهای `[1,2,3]` و `[101,102,103]` پس از تنظیم مرکز چه نسبتی دارند؟ بردار ثابت بدون Epsilon چه خطری دارد؟",
        setup="from torch import nn\nx = torch.tensor([[[1.,2.,3.],[101.,102.,103.]],[[5.,5.,5.],[-1.,0.,4.]]])\nlayer = nn.LayerNorm(3,eps=1e-5)\nwith torch.no_grad():\n    layer.weight.copy_(torch.tensor([1.,2.,0.5]))\n    layer.bias.copy_(torch.tensor([0.1,-0.2,0.3]))\nprint('input:',x)",
        task="تابع `manual_norm(x, gamma, beta, eps)` را بدون `nn.LayerNorm` یا `F.layer_norm` بنویسید. آمار فقط روی محور آخر باشد؛ Shape و محورهای Batch/Time حفظ شوند.",
        starter="def manual_norm(x, gamma, beta, eps):\n    # TODO\n    return None",
        checks="result = manual_norm(x,layer.weight,layer.bias,layer.eps)\nif result is None: return False\ntorch.testing.assert_close(result,layer(x))\ntorch.testing.assert_close(result[0,0],result[0,1])\ntorch.testing.assert_close(result[1,0],layer.bias)\nother = torch.arange(20.).reshape(1,4,5)\nreference = nn.LayerNorm(5)\ntorch.testing.assert_close(manual_norm(other,reference.weight,reference.bias,reference.eps),reference(other))\nassert torch.isfinite(result).all()\nreturn True",
        solution="def manual_norm(x, gamma, beta, eps):\n    mean = x.mean(-1,keepdim=True)\n    variance = x.var(-1,correction=0,keepdim=True)\n    return (x-mean)/torch.sqrt(variance+eps)*gamma+beta",
        vary="فقط به تمام ویژگی‌های موقعیت آخر ۱۰۰ اضافه کنید. با ثابت‌بودن Gamma/Beta، خروجی آن موقعیت تقریباً ثابت می‌ماند؛ بقیهٔ موقعیت‌ها نیز نباید اثر بگیرند.",
        vary_code="changed = x.clone(); changed[:,-1] += 100\nwith torch.no_grad():\n    print('per-position normalized difference:',(layer(changed)-layer(x)).abs().amax(-1))",
        debug="نسخهٔ خراب آمار را روی محور زمان می‌گیرد و موقعیت‌ها را به هم وابسته می‌کند. تابع `normalize_features(x,eps)` را با `Gamma=1` و `Beta=0` اصلاح کنید.",
        bug_code="wrong = (x-x.mean(1,keepdim=True))/torch.sqrt(x.var(1,correction=0,keepdim=True)+1e-5)\nprint('wrong time-axis normalization:',wrong)",
        fix="def normalize_features(x, eps):\n    # TODO\n    return None",
        fix_checks="result = normalize_features(x,1e-5)\nif result is None: return False\ntorch.testing.assert_close(result,nn.LayerNorm(3,elementwise_affine=False)(x))\nconstant = torch.full((1,1,3),5.)\ntorch.testing.assert_close(normalize_features(constant,1e-5),torch.zeros_like(constant))\nreturn True",
        fix_solution="def normalize_features(x, eps):\n    return (x-x.mean(-1,keepdim=True))/torch.sqrt(x.var(-1,correction=0,keepdim=True)+eps)",
        connection="`norm_1`، `norm_2` و `final_norm` در مدل همین قرارداد آخرین محور را دارند. مخلوط‌کردن زمان در محاسبهٔ آمار می‌تواند حتی با وجود Mask علّی در Attention، اطلاعات آینده را وارد گذشته کند.",
        takeaway="پس از Gamma و Beta دلخواه، چرا دیگر نباید برای هر خروجی میانگین دقیقاً صفر و واریانس دقیقاً یک `assert` کنیم؟",
    ),
    "40-block": _lab(
        title="میان‌بر دوم به کجا وصل می‌شود؟",
        goal="Pre-Norm واقعی را بازسازی کنید و خطایی را بگیرید که Shape را عوض نمی‌کند.",
        prerequisite="Attention چندسر، FFN، Residual و LayerNorm را بشناسید.",
        predict="اگر Attention اصلاحی به `x` اضافه کند، FFN باید کدام نمایش را بگیرد و جمع دوم باید با کدام مقدار انجام شود؟",
        setup="from mini_gpt.config import ModelConfig\nfrom mini_gpt.transformer import TransformerBlock\nblock = TransformerBlock(ModelConfig(12,8,8,2,1,0.)).eval()\nx = torch.randn(2,5,8)\ntrace = {}\nwith torch.no_grad():\n    expected = block(x,trace=trace)\nprint('block input/output:',x.shape,expected.shape)",
        task="تابع `manual_block(block,x)` زوج `(after_attention, output)` برگرداند. زیرلایه‌های خود `block` را به کار ببرید، ولی `block(x)` را صدا نزنید. ترتیب Pre-Norm و هر دو Residual را حفظ کنید.",
        starter="def manual_block(block, x):\n    # TODO\n    return None",
        checks="result = manual_block(block,x)\nif result is None: return False\nafter_attention,out = result\ntorch.testing.assert_close(out,expected)\ntorch.testing.assert_close(after_attention,x+block.attention(block.norm_1(x)))\ntorch.testing.assert_close(out-after_attention,trace['feed_forward'])\ny = torch.randn(1,3,8)\ntorch.testing.assert_close(manual_block(block,y)[1],block(y))\nreturn True",
        solution="def manual_block(block, x):\n    after_attention = x+block.attention(block.norm_1(x))\n    output = after_attention+block.feed_forward(block.norm_2(after_attention))\n    return after_attention, output",
        vary="فقط `residual` را روی همان بلوک خاموش کنید. در این API هر دو جمع حذف می‌شوند؛ LayerNorm و Mask باقی می‌مانند. از این اختلاف عددی به‌تنهایی نمی‌توان دربارهٔ کیفیت آموزش نتیجه گرفت.",
        vary_code="with torch.no_grad():\n    without = block(x,residual=False)\n    manual_without = block.feed_forward(block.norm_2(block.attention(block.norm_1(x))))\n    torch.testing.assert_close(without,manual_without)\n    print('same shape:',without.shape,'difference:',(without-expected).abs().mean().item())",
        debug="نسخهٔ خراب جمع دوم را دوباره به ورودی آغاز بلوک وصل می‌کند. تابع `repair_block(block,x)` فقط خروجی نهایی صحیح را برگرداند.",
        bug_code="with torch.no_grad():\n    middle = x+block.attention(block.norm_1(x))\n    wrong = x+block.feed_forward(block.norm_2(middle))\nprint('same shape:',wrong.shape,'wrong skip difference:',(wrong-expected).abs().max().item())",
        fix="def repair_block(block, x):\n    # TODO\n    return None",
        fix_checks="result = repair_block(block,x)\nif result is None: return False\ntorch.testing.assert_close(result,expected)\nfor T in (1,4):\n    y = torch.randn(1,T,8)\n    torch.testing.assert_close(repair_block(block,y),block(y))\nreturn True",
        fix_solution="def repair_block(block, x):\n    y = x+block.attention(block.norm_1(x))\n    return y+block.feed_forward(block.norm_2(y))",
        connection="`TransformerBlock` واقعی هم در v5 و هم در `MiniGPT` استفاده می‌شود. `trace['feed_forward']` اصلاح FFN پیش از جمع است، نه خروجی نهایی بلوک؛ این تفاوت در آزمون میانی سنجیده شد.",
        takeaway="کدام مقایسه نشان داد بلوک فقط هم‌شکل نیست، بلکه همان محاسبهٔ مرجع را انجام می‌دهد؟",
    ),
    "41-stack": _lab(
        title="دو بلوک مستقل یا یک بلوک دوبار؟",
        goal="Stack ثبت‌شده با وزن‌های مستقل بسازید و تعداد پارامترهایش را کنترل کنید.",
        prerequisite="ساخت نمونهٔ کلاس، `ModuleList` و قرارداد ورودی/خروجی بلوک را بشناسید.",
        predict="`nn.ModuleList([block,block])` چند مجموعه وزن مستقل دارد؟ اگر یک بلوک را تغییر دهید، بلوک دوم چه می‌شود؟",
        setup="from torch import nn\nfrom mini_gpt.config import ModelConfig\nfrom mini_gpt.transformer import TransformerBlock\nconfig = ModelConfig(12,8,8,2,1,0.)\nprototype = TransformerBlock(config)\nper_block = sum(p.numel() for p in prototype.parameters())\nprint('one block parameters:',per_block)",
        task="تابع `make_stack(config, count)` یک `nn.ModuleList` با `count` نمونهٔ مستقل `TransformerBlock` بسازد. `count` در این تمرین مثبت است؛ از تکرار یک شیء در فهرست استفاده نکنید.",
        starter="def make_stack(config, count):\n    # TODO\n    return None",
        checks="stack = make_stack(config,2)\nif stack is None: return False\nassert isinstance(stack,nn.ModuleList) and len(stack) == 2\nassert stack[0] is not stack[1]\nassert stack[0].attention.qkv.weight is not stack[1].attention.qkv.weight\ncontainer = nn.Module(); container.blocks = stack\nassert sum(p.numel() for p in container.parameters()) == 2*per_block\nbefore = stack[1].attention.qkv.weight.detach().clone()\nwith torch.no_grad(): stack[0].attention.qkv.weight.add_(1.)\nassert torch.equal(stack[1].attention.qkv.weight,before)\nassert sum(p.numel() for p in make_stack(config,3).parameters()) == 3*per_block\nreturn True",
        solution="def make_stack(config, count):\n    return nn.ModuleList([TransformerBlock(config) for _ in range(count)])",
        vary="فقط `num_layers` را در `MiniGPT` از ۱ به ۲ و ۳ تغییر دهید. جدول‌های ورودی و خروجی فقط یک بار ساخته می‌شوند؛ انتظار برابری Logits مدل‌های تازه نداریم.",
        vary_code="from mini_gpt.model import MiniGPT\nfor L in (1,2,3):\n    model = MiniGPT(ModelConfig(12,8,8,2,L,0.)).eval()\n    print('layers, parameters:',L,sum(p.numel() for p in model.parameters()))",
        debug="نسخهٔ خراب یک نمونه را دوبار ثبت می‌کند. تابع `independent_pair(config)` دو بلوک مستقل در `ModuleList` برگرداند؛ صرفاً کپی‌کردن فهرست Python کافی نیست.",
        bug_code="shared = TransformerBlock(config)\nwrong = nn.ModuleList([shared,shared])\nprint('same object:',wrong[0] is wrong[1])\nprint('unique parameters:',sum(p.numel() for p in wrong.parameters()),'expected independent:',2*per_block)",
        fix="def independent_pair(config):\n    # TODO\n    return None",
        fix_checks="result = independent_pair(config)\nif result is None: return False\nassert isinstance(result,nn.ModuleList) and len(result) == 2\nassert result[0] is not result[1]\nassert sum(p.numel() for p in result.parameters()) == 2*per_block\nassert not ({id(p) for p in result[0].parameters()} & {id(p) for p in result[1].parameters()})\nreturn True",
        fix_solution="def independent_pair(config):\n    return nn.ModuleList([TransformerBlock(config),TransformerBlock(config)])",
        connection="`MiniGPT.blocks` از همین الگوی ساخت مستقل استفاده می‌کند. v6 تنظیم کوچکِ مدل نهایی است؛ `ModuleList` پارامترها را ثبت می‌کند، اما حلقهٔ `forward` باید جداگانه خروجی هر بلوک را به بعدی بدهد.",
        takeaway="چرا تعداد فراخوانی بلوک لزوماً تعداد مجموعه‌های مستقل پارامتر را نشان نمی‌دهد؟",
    ),
    "42-families": _lab(
        title="سه معماری را با مسیر اطلاعات تشخیص دهید",
        goal="خودتوجهی دوطرفه، خودتوجهی علّی و Cross-Attention مستطیلی را با عدد مقایسه کنید.",
        prerequisite="`Q/K/V`، Mask و شکل ضرب Attention را بشناسید؛ منبع و هدف دو دنبالهٔ متفاوت‌اند.",
        predict="منبع ۵ موقعیت و خروجی فعلی ۳ موقعیت دارد. چرا بستن ستون‌های بعد از قطر در Cross-Attention، بخشی از منبعِ ازپیش‌موجود را بی‌دلیل پنهان می‌کند؟",
        setup="source = torch.tensor([[1.,0.],[0.,1.],[1.,1.],[-1.,0.],[0.,-1.]])\ntarget = torch.tensor([[1.,0.],[0.,1.],[1.,1.]])\nprint('source/target lengths:',len(source),len(target))",
        task="تابع `family_attention(q,k,v,kind)` زوج `(weights,output)` برگرداند. `kind` برابر `encoder` یا `decoder` یا `cross` است. فقط در `decoder` جدول مربعی را علّی کنید؛ در دو حالت دیگر همهٔ Keyها مجازند. `q` و `k` دو ویژگی مشترک دارند، ولی تعداد سطرهایشان می‌تواند متفاوت باشد.",
        starter="def family_attention(q, k, v, kind):\n    # TODO\n    return None",
        checks="result = family_attention(target,source,source,'cross')\nif result is None: return False\nw,out = result\nassert w.shape == (3,5) and out.shape == (3,2)\ntorch.testing.assert_close(w,(target@source.T/math.sqrt(2)).softmax(-1))\ntorch.testing.assert_close(out,w@source)\nwe,_ = family_attention(source,source,source,'encoder')\nassert we.shape == (5,5) and (we > 0).all()\nwd,_ = family_attention(target,target,target,'decoder')\nassert torch.count_nonzero(wd.triu(1)) == 0\ntorch.testing.assert_close(wd.sum(-1),torch.ones(3))\nzq,zk,zv = torch.zeros(2,4),torch.zeros(3,4),torch.tensor([[1.],[2.],[6.]])\ntorch.testing.assert_close(family_attention(zq,zk,zv,'cross')[1],torch.full((2,1),3.))\nreturn True",
        solution="def family_attention(q, k, v, kind):\n    scores = q@k.T/math.sqrt(q.shape[-1])\n    if kind == 'decoder':\n        allowed = torch.ones(scores.shape,dtype=torch.bool,device=scores.device).tril()\n        scores = scores.masked_fill(~allowed,float('-inf'))\n    weights = scores.softmax(-1)\n    return weights, weights@v",
        vary="فقط طول منبع را از ۵ به ۴ کاهش دهید؛ Queryهای خروجی ثابت بمانند. تعداد سطرهای Cross-Attention از هدف و تعداد ستون‌ها از منبع می‌آیند.",
        vary_code="for length in (5,4):\n    weights = (target@source[:length].T/math.sqrt(2)).softmax(-1)\n    print('source length, weights/output shapes:',length,weights.shape,(weights@source[:length]).shape)",
        debug="کد خراب Mask علّیِ هدف را به جدول Cross-Attention تعمیم می‌دهد. تابع `cross_weights(q,k)` را اصلاح کنید؛ تمام منبع در این مثال از ابتدا موجود است.",
        bug_code="scores = target@source.T/math.sqrt(2)\nwrong = scores.masked_fill(~torch.ones(3,5,dtype=torch.bool).tril(),float('-inf')).softmax(-1)\nprint('wrong: source positions hidden from first target:',wrong[0])",
        fix="def cross_weights(q, k):\n    # TODO\n    return None",
        fix_checks="result = cross_weights(target,source)\nif result is None: return False\ntorch.testing.assert_close(result,(target@source.T/math.sqrt(2)).softmax(-1))\nassert (result > 0).all()\ntorch.testing.assert_close(cross_weights(torch.zeros(2,3),torch.zeros(4,3)),torch.full((2,4),0.25))\nreturn True",
        fix_solution="def cross_weights(q, k):\n    return (q@k.T/math.sqrt(q.shape[-1])).softmax(-1)",
        connection="`MiniGPT` از حالت Decoder-only استفاده می‌کند: در هر بلوک `Q/K/V` از یک جریان‌اند و Mask علّی داریم. پروژه Encoder یا Cross-Attention جدا ندارد؛ تابع کوچک این دفتر صرفاً برای مقایسهٔ خانواده‌هاست.",
        takeaway="اگر کسی Transformer را مساوی GPT بداند، کدام تفاوتِ قابل مشاهده در این دفتر را از دست داده است؟",
    ),
    "43-lm-head": _lab(
        title="هر سطر Logits باید هدف خودش را داشته باشد",
        goal="خروجی Language-model head و Loss را با حفظ تطابق Batch/Time بسازید.",
        prerequisite="Linear، Logits، Cross entropy و هدف یک‌خانه‌جلو را بشناسید.",
        predict="برای `B=2` و `T=3`، هدفِ `(1,0)` پس از صاف‌کردن در کدام سطر است؟ اگر فقط Target را `transpose` کنیم، Shape خطا را آشکار می‌کند؟",
        setup="from torch.nn import functional as F\nfrom mini_gpt.config import ModelConfig\nfrom mini_gpt.model import MiniGPT\nmodel = MiniGPT(ModelConfig(7,6,8,2,1,0.)).eval()\nhidden = torch.randn(2,3,8)\ntargets = torch.tensor([[1,2,3],[4,5,6]])\nprint('head weight:',model.language_model_head.weight.shape,'targets:',targets)",
        task="تابع `prediction_loss(hidden, weight, targets)` زوج `(logits, loss)` برگرداند. `weight` همان وزن `(V,C)` بدون Bias است؛ Logits را خودتان ضرب کنید و برای Loss، `B` و `T` را در هر دو ورودی با ترتیب یکسان صاف کنید. پیش از `F.cross_entropy`، Softmax نزنید.",
        starter="def prediction_loss(hidden, weight, targets):\n    # TODO\n    return None",
        checks="result = prediction_loss(hidden,model.language_model_head.weight,targets)\nif result is None: return False\nlogits,loss = result\ntorch.testing.assert_close(logits,model.language_model_head(hidden))\nseparate = torch.stack([F.cross_entropy(logits[b,t][None],targets[b,t][None]) for b in range(2) for t in range(3)]).mean()\ntorch.testing.assert_close(loss,separate)\nx = torch.randn(1,4,3); w = torch.randn(5,3); y = torch.tensor([[0,1,2,3]])\nz,l = prediction_loss(x,w,y)\ntorch.testing.assert_close(z,x@w.T)\ntorch.testing.assert_close(l,F.cross_entropy(z.reshape(-1,5),y.reshape(-1)))\nreturn True",
        solution="def prediction_loss(hidden, weight, targets):\n    logits = hidden@weight.T\n    loss = F.cross_entropy(logits.reshape(-1,weight.shape[0]),targets.reshape(-1))\n    return logits, loss",
        vary="فقط Vocabulary را از ۷ به ۱۰ افزایش دهید؛ `C` ثابت است. اینجا فقط تعداد امتیازها و پارامترهای Head را مقایسه می‌کنیم، نه کیفیت مدل‌های تصادفی تازه را.",
        vary_code="from torch import nn\nfor V in (7,10):\n    head = nn.Linear(8,V,bias=False)\n    print('V, output shape, parameters:',V,head(hidden).shape,sum(p.numel() for p in head.parameters()))",
        debug="دادهٔ کنترل‌شدهٔ زیر برای هر سطر، امتیاز کلاس درست را بالا گذاشته است. شش کلاس دیگر هرکدام ۸ واحد امتیاز کمتر دارند؛ بنابراین Loss درست هر سطر حدود ۰٫۰۰۲ است. کد خراب Target را با ترتیب زمان-اول صاف می‌کند. تابع `aligned_loss(logits,targets)` را اصلاح کنید.",
        bug_code="fixture = torch.full((2,3,7),-4.)\nfixture.scatter_(-1,targets[...,None],4.)\nwrong = F.cross_entropy(fixture.reshape(-1,7),targets.T.reshape(-1))\ncorrect = fixture.new_tensor(math.log1p(6*math.exp(-8.)))\nprint('wrong ordering/known expected loss:',wrong.item(),correct.item())\nassert wrong.item() > 1.",
        fix="def aligned_loss(logits, targets):\n    # TODO\n    return None",
        fix_checks="result = aligned_loss(fixture,targets)\nif result is None: return False\ntorch.testing.assert_close(result,correct)\nassert result.item() < 0.01\nlogits = torch.tensor([[[1.,2.],[3.,-1.]]])\ny = torch.tensor([[1,0]])\ntorch.testing.assert_close(aligned_loss(logits,y),F.cross_entropy(logits[0],y[0]))\nreturn True",
        fix_solution="def aligned_loss(logits, targets):\n    return F.cross_entropy(logits.reshape(-1,logits.shape[-1]),targets.reshape(-1))",
        connection="`language_model_head` و محاسبهٔ نهایی Loss در `MiniGPT` همین قرارداد را دارند. `hidden` واقعی مدل پس از `final_norm` می‌آید؛ اینجا نمایش کوچکِ آماده دادیم تا خطای تطابق سطرها جدا دیده شود.",
        takeaway="چرا Loss عددی و Shape درست برای تأیید جفت‌شدن هر پیش‌بینی با هدف درست کافی نیست؟",
    ),
    "44-parameters": _lab(
        title="کدام عددها واقعاً آموخته می‌شوند؟",
        goal="شمارش معماری را با پارامترهای واقعی بسنجید و Buffer را از وزن جدا کنید.",
        prerequisite="اندازهٔ Embedding، Linear، LayerNorm و تعداد بلوک‌ها را بشناسید.",
        predict="اگر فقط `H` عوض شود ولی `C` ثابت بماند، وزن‌های QKV بزرگ‌تر می‌شوند؟ آیا هر Tensor موجود در `state_dict` قابل آموزش است؟",
        setup="from mini_gpt.config import ModelConfig\nfrom mini_gpt.model import MiniGPT\nconfig = ModelConfig(12,8,16,2,2,0.)\nmodel = MiniGPT(config)\nprint('parameter tensors:',len(list(model.parameters())))\nprint('buffers:',[(name,tuple(value.shape)) for name,value in model.named_buffers()])\nprint('initial embedding std (small sample):',model.token_embedding.weight.detach().std().item())",
        task="تابع `parameter_formula(config)` را از ابعاد Config بنویسید و یک `int` برگردانید. سهم دو جدول `V*C`، جدول موقعیت، `L` بلوک و LayerNorm نهایی را جدا حساب کنید؛ در این تابع مدل نسازید و `parameters` را نشمارید.",
        starter="def parameter_formula(config):\n    # TODO\n    return None",
        checks="result = parameter_formula(config)\nif result is None: return False\nassert result == 7104\nfor cfg in (config,ModelConfig(9,5,12,3,1,0.),ModelConfig(15,7,8,4,3,0.)):\n    actual = MiniGPT(cfg)\n    assert parameter_formula(cfg) == sum(p.numel() for p in actual.parameters())\nassert parameter_formula(ModelConfig(12,8,16,4,2,0.)) == result\nreturn True",
        solution="def parameter_formula(config):\n    V,T,C,L = config.vocab_size,config.context_length,config.embedding_dim,config.num_layers\n    embeddings_and_head = 2*V*C+T*C\n    blocks = L*(12*C*C+13*C)\n    final_norm = 2*C\n    return embeddings_and_head+blocks+final_norm",
        vary="فقط `H` را میان ۱، ۲ و ۴ تغییر دهید؛ اندازهٔ `C` و بقیهٔ Config ثابت‌اند. مقداردهی تصادفی مدل‌های تازه ربطی به شمار پارامترها ندارد.",
        vary_code="for H in (1,2,4):\n    candidate = MiniGPT(ModelConfig(12,8,16,H,2,0.))\n    print('H, parameters:',H,sum(p.numel() for p in candidate.parameters()))",
        debug="کد خراب Buffer پوشش علّی را هم وزن آموختنی شمرده است. تابع `trainable_count(module)` فقط پارامترهای `requires_grad=True` را بشمارد؛ ممکن است `requires_grad` بعضی وزن‌ها عمداً `False` شده باشد تا آموزش نبینند.",
        bug_code="print('all state tensors:',sum(value.numel() for value in model.state_dict().values()))\nprint('parameters only:',sum(p.numel() for p in model.parameters()))",
        fix="def trainable_count(module):\n    # TODO\n    return None",
        fix_checks="result = trainable_count(model)\nif result is None: return False\nassert result == 7104\nmodel.token_embedding.weight.requires_grad_(False)\ntry:\n    assert trainable_count(model) == 7104-model.token_embedding.weight.numel()\nfinally:\n    model.token_embedding.weight.requires_grad_(True)\nassert trainable_count(model.final_norm) == 32\nreturn True",
        fix_solution="def trainable_count(module):\n    return sum(p.numel() for p in module.parameters() if p.requires_grad)",
        connection="فرمول برای `MiniGPT` همین مخزن است: Head بدون Bias و بدون اشتراک وزن با Embedding، FFN با عرض `4C` و دو LayerNorm در هر بلوک. برای معماری دیگری باید فرمول را دوباره بسازید.",
        takeaway="چه تفاوتی میان «پارامتر مدل»، «پارامتر قابل آموزش در این اجرا» و «همهٔ Tensorهای ذخیره‌شده» پیدا کردید؟",
    ),
    "45-trace": _lab(
        title="Logits را از مسیر واقعی مدل بازسازی کنید",
        goal="Embedding، موقعیت، بلوک‌ها و Head را با `trace` همان مدل تطبیق دهید.",
        prerequisite="تمام اجزای `MiniGPT` و تفاوت `trace` با یک محاسبهٔ جداگانه را بشناسید.",
        predict="آیا ورودی Attention بلوک اول همان Token Embedding خام است؟ کدام دو عملیات پیش از آن انجام می‌شوند؟",
        setup="from mini_gpt.config import ModelConfig\nfrom mini_gpt.model import MiniGPT\nmodel = MiniGPT(ModelConfig(12,8,8,2,2,0.)).eval()\nids = torch.tensor([[1,2,3,4]])\nreference_trace = {}\nwith torch.no_grad():\n    reference_logits,_ = model(ids,trace=reference_trace)\nprint('trace fields:',list(reference_trace))",
        task="تابع `trace_logits(model, ids, use_positions=True)` دیکشنری با کلیدهای `combined`، `block_outputs` و `logits` برگرداند. `combined` جمع ورودی پیش از Dropout، `block_outputs` فهرست خروجی همهٔ بلوک‌ها و `logits` خروجی Head پس از `final_norm` باشد. از زیرلایه‌ها استفاده کنید، نه `model(ids)`.",
        starter="def trace_logits(model, ids, use_positions=True):\n    # TODO\n    return None",
        checks="result = trace_logits(model,ids)\nif result is None: return False\nfor tokens in (ids,torch.tensor([[4,3,2],[2,1,2]])):\n    for positions in (False,True):\n        actual = trace_logits(model,tokens,use_positions=positions)\n        trace = {}; logits,_ = model(tokens,use_positions=positions,trace=trace)\n        torch.testing.assert_close(actual['combined'],trace['combined_embedding'])\n        assert len(actual['block_outputs']) == len(model.blocks)\n        for a,b in zip(actual['block_outputs'],trace['layers']):\n            torch.testing.assert_close(a,b['output'])\n        torch.testing.assert_close(actual['logits'],logits)\nreturn True",
        solution="def trace_logits(model, ids, use_positions=True):\n    combined = model.token_embedding(ids)\n    if use_positions:\n        positions = torch.arange(ids.shape[1],device=ids.device)\n        combined = combined+model.position_embedding(positions)\n    hidden = model.dropout(combined)\n    outputs = []\n    for block in model.blocks:\n        hidden = block(hidden)\n        outputs.append(hidden)\n    logits = model.language_model_head(model.final_norm(hidden))\n    return {'combined':combined,'block_outputs':outputs,'logits':logits}",
        vary="فقط `use_positions` را روی همان مدل خاموش کنید. شکل‌ها ثابت می‌مانند، ولی مسیر ورودی تغییر می‌کند. این حذف کنترل‌شدهٔ موقعیت به‌تنهایی دربارهٔ کیفیت زبان یا بی‌اهمیت‌بودن ترتیب حکم نمی‌دهد.",
        vary_code="with torch.no_grad():\n    with_positions = model(ids,use_positions=True)[0]\n    without_positions = model(ids,use_positions=False)[0]\nprint('same shape:',with_positions.shape == without_positions.shape)\nprint('position ablation change:',(with_positions-without_positions).abs().max().item())",
        debug="نسخهٔ خراب Attention را روی Embedding خام اجرا می‌کند. تابع `first_attention_input(model,ids)` فقط ورودی صحیحِ Attention بلوک اول را برگرداند: جمع موقعیت، Dropout ورودی و `norm_1` را فراموش نکنید.",
        bug_code="with torch.no_grad():\n    wrong_input = model.token_embedding(ids)\n    correct_input = model.blocks[0].norm_1(reference_trace['layers'][0]['input'])\nprint('raw embedding/input difference:',(wrong_input-correct_input).abs().max().item())",
        fix="def first_attention_input(model, ids):\n    # TODO\n    return None",
        fix_checks="result = first_attention_input(model,ids)\nif result is None: return False\ntorch.testing.assert_close(result,correct_input)\nfor tokens in (torch.tensor([[2]]),torch.tensor([[2,3],[4,5]])):\n    trace = {}; model(tokens,trace=trace)\n    torch.testing.assert_close(first_attention_input(model,tokens),model.blocks[0].norm_1(trace['layers'][0]['input']))\nreturn True",
        fix_solution="def first_attention_input(model, ids):\n    positions = torch.arange(ids.shape[1],device=ids.device)\n    hidden = model.dropout(model.token_embedding(ids)+model.position_embedding(positions))\n    return model.blocks[0].norm_1(hidden)",
        connection="`trace` از `forward` واقعی `MiniGPT` می‌آید و مسیر دستی با تک‌تک خروجی‌های بلوک تطبیق داده شد. مدل `eval` و Dropout صفر است تا اختلاف تصادف را با اختلاف معماری اشتباه نگیریم.",
        takeaway="اگر فقط Logits نهایی متفاوت بود، کدام مقایسهٔ میانی به شما کمک می‌کرد اولین نقطهٔ انحراف را پیدا کنید؟",
    ),
    "46-gradient-path": _lab(
        title="خروجی سالم، مسیر یادگیری قطع‌شده",
        goal="`None` و Gradient صفر را تشخیص دهید و محل قطع مسیر پیش از Head را پیدا کنید.",
        prerequisite="`backward`، `zero_grad`، `detach` و Norm را بشناسید.",
        predict="با `detach`کردن `hidden` پیش از Head، کدام پارامترها هنوز Gradient می‌گیرند؟ آیا Shape خروجی باید تغییر کند؟",
        setup='''
        from torch.nn import functional as F
        from mini_gpt.config import ModelConfig
        from mini_gpt.model import MiniGPT
        model = MiniGPT(ModelConfig(12,8,8,2,2,0.)).eval()
        ids = torch.tensor([[1,2,3,4]])
        targets = torch.tensor([[2,3,4,5]])
        def features(model, ids):
            positions = torch.arange(ids.shape[1])
            hidden = model.dropout(model.token_embedding(ids)+model.position_embedding(positions))
            for block in model.blocks:
                hidden = block(hidden)
            return model.final_norm(hidden)
        print("tracked endpoints: token_embedding.weight / language_model_head.weight")
        ''',
        task="تابع `gradient_report(model)` دیکشنری نام پارامتر به `None` یا `float` اندازهٔ Gradient برگرداند. `None` را به صفر تبدیل نکنید. خود تابع `forward` یا `backward` اجرا نکند و مشتق‌ها را تغییر ندهد.",
        starter="def gradient_report(model):\n    # TODO\n    return None",
        checks="model.zero_grad(set_to_none=True)\nresult = gradient_report(model)\nif result is None: return False\nassert set(result) == {name for name,_ in model.named_parameters()}\nassert all(value is None for value in result.values())\nmodel(ids,targets)[1].backward()\nreport = gradient_report(model)\nassert all(value is not None and math.isfinite(value) for value in report.values())\nfor name,p in model.named_parameters():\n    assert abs(report[name]-p.grad.norm().item()) < 1e-8\nmodel.zero_grad(set_to_none=True)\n(model(ids,targets)[1]*0).backward()\nassert all(value == 0. for value in gradient_report(model).values())\nreturn True",
        solution="def gradient_report(model):\n    return {name:None if parameter.grad is None else parameter.grad.norm().item() for name,parameter in model.named_parameters()}",
        vary="این بار از `forward` کامل مدل استفاده کنید و فقط ضریب Loss را از یک به صفر تغییر دهید؛ وزن و Batch ثابت باشند. پیش از هر `backward` مشتق‌ها را با `set_to_none=True` پاک کنید. وقتی Gradient صفر می‌شود، آیا هنوز Tensor موجودی داریم یا مقدار آن `None` شده است؟",
        vary_code="for loss_scale in (1.,0.):\n    model.zero_grad(set_to_none=True)\n    _,loss = model(ids,targets)\n    (loss_scale*loss).backward()\n    embedding_gradient = model.token_embedding.weight.grad\n    print('loss scale, gradient missing, nonzero entries:',loss_scale,embedding_gradient is None,torch.count_nonzero(embedding_gradient).item())",
        debug="کد خراب مقدار `hidden` را درست نگه می‌دارد ولی ارتباط آن با لایه‌های قبلی را قطع می‌کند. تابع `connected_head_loss(model,hidden,targets)` را بدون `detach` اصلاح کنید؛ خود Tensor مربوط به Loss را برگردانید، نه مقدار حاصل از `item()`.",
        bug_code="model.zero_grad(set_to_none=True)\nhidden = features(model,ids)\nwrong_logits = model.language_model_head(hidden.detach())\nF.cross_entropy(wrong_logits.reshape(-1,12),targets.reshape(-1)).backward()\nprint('valid logits shape:',wrong_logits.shape,'embedding grad:',model.token_embedding.weight.grad)",
        fix="def connected_head_loss(model, hidden, targets):\n    # TODO\n    return None",
        fix_checks="model.zero_grad(set_to_none=True)\nhidden = features(model,ids)\nresult = connected_head_loss(model,hidden,targets)\nif result is None: return False\ntorch.testing.assert_close(result,model(ids,targets)[1])\nresult.backward()\nassert model.token_embedding.weight.grad is not None\nassert model.language_model_head.weight.grad is not None\nassert all(p.grad is not None and torch.isfinite(p.grad).all() for p in model.parameters())\nmodel.zero_grad(set_to_none=True)\nother_ids,other_targets = ids[:,:2],targets[:,:2]\nloss = connected_head_loss(model,features(model,other_ids),other_targets)\nloss.backward()\nassert model.blocks[0].attention.qkv.weight.grad is not None\nreturn True",
        fix_solution="def connected_head_loss(model, hidden, targets):\n    logits = model.language_model_head(hidden)\n    return F.cross_entropy(logits.reshape(-1,logits.shape[-1]),targets.reshape(-1))",
        connection="`test_all_parameters_receive_gradients` در `tests/test_model.py` مسیر سالم مدل را می‌سنجد. این دفتر علاوه بر آن، همان وزن‌ها را با یک قطع عمدی آزمایش کرد تا معنای هر Gradient موجود یا غایب روشن شود.",
        takeaway="اگر پس از صفرکردن Loss مشتق صفر دارید ولی پس از `detach` مشتق `None`، این دو مشاهده دربارهٔ ساختار مسیر چه تفاوتی دارند؟",
    ),
}
