"""Synthesis exercises appended to, never replacing, the twelve review labs."""

from .attention import _lab


EXERCISES = {
    "01_matrix_products": _lab(
        title="اثر یک تغییر را بدون تکرار کل ضرب حساب کنید",
        goal="از معنای ضرب ماتریسی برای پیش‌بینی محل و مقدار تغییر خروجی استفاده کنید.",
        prerequisite="نمونهٔ سطر و ستون در همین دفتر را اجرا کرده باشید.",
        predict="اگر فقط A[i,k] به اندازهٔ delta زیاد شود، چه ارتباطی میان تغییر سطر i خروجی و سطر k ماتریس B وجود دارد؟",
        setup="a = [[1.,2.,3.],[4.,5.,6.]]\nb = [[1.,2.],[3.,4.],[5.,6.]]\nprint('A:',a,'B:',b)",
        task="تابع product_change(rows,b,i,k,delta) فقط ماتریس اختلاف خروجی را با list برگرداند. rows تعداد سطرهای A است؛ بدون ساخت A یا تکرار matmul، سهم تغییر یک خانه را حساب کنید.",
        starter="def product_change(rows, b, i, k, delta):\n    # TODO\n    return None",
        checks="result = product_change(2,b,0,1,2.)\nif result is None: return False\nassert result == [[6.,8.],[0.,0.]]\nassert product_change(3,[[2.,-1.,4.]],2,0,-0.5) == [[0.,0.,0.],[0.,0.,0.],[-1.,0.5,-2.]]\nassert product_change(1,b,0,2,0.) == [[0.,0.]]\nreturn True",
        solution="def product_change(rows, b, i, k, delta):\n    result = [[0. for _ in b[0]] for _ in range(rows)]\n    result[i] = [delta*value for value in b[k]]\n    return result",
        vary="فقط delta را از ۱ به ۲ و منفی ۱ تغییر دهید. محل اثر ثابت است؛ مقدار و علامت آن چه می‌شود؟",
        vary_code="for delta in (1.,2.,-1.):\n    print('delta and changed output row:',delta,[delta*value for value in b[1]])",
        debug="با [[0]*cols]*rows همهٔ سطرها یک شیء می‌شوند. تابع zero_matrix(rows,cols) را اصلاح کنید تا دست‌کاری یک سطر به دیگری سرایت نکند.",
        bug_code="wrong = [[0.]*2]*3\nwrong[0][0] = 9.\nprint('aliased rows:',wrong)",
        fix="def zero_matrix(rows, cols):\n    # TODO\n    return None",
        fix_checks="result = zero_matrix(3,2)\nif result is None: return False\nassert result == [[0.,0.],[0.,0.],[0.,0.]]\nresult[0][0] = 7.\nassert result[1][0] == result[2][0] == 0.\nassert zero_matrix(1,3) == [[0.,0.,0.]]\nreturn True",
        fix_solution="def zero_matrix(rows, cols):\n    return [[0. for _ in range(cols)] for _ in range(rows)]",
        connection="در Projectionهای MiniGPT نیز هر مؤلفهٔ ورودی از راه یک ردیف یا ستون وزن به چند خروجی سهم می‌دهد. این تمرین مسیر اثر را پیش از ورود به Tensorها قابل محاسبه می‌کند.",
        takeaway="چرا تغییر یک خانهٔ A گاهی چند خانهٔ خروجی را عوض می‌کند، با اینکه در مثال اولیهٔ دفتر فقط یک خانه تغییر کرد؟",
    ),
    "02_probability_loss": _lab(
        title="هدف عوض شد، توزیع نه",
        goal="اثر تغییر Target را از اثر تغییر Logits جدا کنید.",
        prerequisite="Softmax و Loss یک هدف در بخش‌های قبلی همین دفتر را بشناسید.",
        predict="Logits برابر [2,1,0] ثابت‌اند. اگر هدف از کلاس صفر به دو برود، اختلاف Loss چقدر است؟ لازم است Softmax را دوباره حساب کنیم؟",
        setup="logits = [2.,1.,0.]\nprint('fixed logits:',logits)",
        task="تابع target_loss_change(logits, old_target, new_target) مقدار Loss جدید منهای قبلی را فقط از امتیازها حساب کند؛ نرمال‌ساز در تفاضل حذف می‌شود. ورودی‌ها شناسهٔ معتبر کلاس‌اند.",
        starter="def target_loss_change(logits, old_target, new_target):\n    # TODO\n    return None",
        checks="result = target_loss_change(logits,0,2)\nif result is None: return False\nassert result == 2.\nassert target_loss_change([1002.,1001.,1000.],0,2) == 2.\nassert target_loss_change([-3.,4.,1.],2,1) == -3.\nassert target_loss_change(logits,1,1) == 0.\nreturn True",
        solution="def target_loss_change(logits, old_target, new_target):\n    return logits[old_target]-logits[new_target]",
        vary="فقط شناسهٔ هدف را تغییر دهید؛ امتیاز و احتمال ثابت باشند. مقدار منفیِ اختلاف Loss چه معنایی دارد؟",
        vary_code="maximum = max(logits)\nnormalizer = maximum+math.log(sum(math.exp(z-maximum) for z in logits))\nfor target in range(len(logits)):\n    print('target, loss:',target,normalizer-logits[target])",
        debug="شمارهٔ کلاس اندازهٔ پاسخ نیست؛ کد خراب فاصلهٔ عددی دو ID را Loss می‌نامد. تابع surprise(probabilities,target) باید منفی لگاریتم احتمال هدف را برگرداند؛ همهٔ احتمال‌ها در این تمرین مثبت‌اند.",
        bug_code="probabilities = [0.1,0.2,0.7]\nprint('wrong ID distance:',abs(0-2),'actual target-0 surprise:',-math.log(probabilities[0]))",
        fix="def surprise(probabilities, target):\n    # TODO\n    return None",
        fix_checks="result = surprise(probabilities,0)\nif result is None: return False\nassert math.isclose(result,-math.log(0.1))\nassert surprise([1.],0) == 0.\nassert math.isclose(surprise([0.8,0.2],1),-math.log(0.2))\nreturn True",
        fix_solution="def surprise(probabilities, target):\n    return -math.log(probabilities[target])",
        connection="در MiniGPT نیز Target یک شناسهٔ Vocabulary است؛ اختلاف عددی IDها هیچ معنای شباهت زبانی ندارد. Cross entropy احتمال همان شناسهٔ هدف را مصرف می‌کند.",
        takeaway="چطور یک توزیع یکسان می‌تواند برای دو Target، دو Loss متفاوت داشته باشد؟",
    ),
    "03_tensor_shapes": _lab(
        title="آمار هر موقعیت را نگه دارید، سپس سطرها را بسته‌بندی کنید",
        goal="Broadcasting و reshape را در یک مسیر با نشانی قابل پیگیری ترکیب کنید.",
        prerequisite="B، T، C و keepdim در همین دفتر معرفی شده‌اند.",
        predict="اگر از هر بردار Cتایی میانگین خودش را کم کنیم، ردیف b*T+t در خروجی صاف‌شده متعلق به کدام موقعیت است؟",
        setup="batch = torch.tensor([[[1.,2.,6.],[10.,20.,30.]],[[0.,3.,9.],[-2.,1.,4.]]])\nprint('B,T,C:',batch.shape)",
        task="تابع center_and_pack(x) ابتدا هر بردار آخرین محور را حول میانگین خودش مرکز کند، سپس (B,T,C) را به (B*T,C) ببرد. ترتیب نمونه و زمان حفظ شود.",
        starter="def center_and_pack(x):\n    # TODO\n    return None",
        checks="result = center_and_pack(batch)\nif result is None: return False\nassert result.shape == (4,3)\nfor b in range(2):\n    for t in range(2):\n        torch.testing.assert_close(result[b*2+t],batch[b,t]-batch[b,t].mean())\nx = torch.arange(40.).reshape(2,5,4)\ntorch.testing.assert_close(center_and_pack(x).mean(-1),torch.zeros(10))\nreturn True",
        solution="def center_and_pack(x):\n    centered = x-x.mean(-1,keepdim=True)\n    return centered.reshape(-1,x.shape[-1])",
        vary="فقط مرکز یک موقعیت را با افزودن ۱۰۰ به همهٔ ویژگی‌هایش تغییر دهید. خروجی مرکز‌شدهٔ آن باید تقریباً ثابت بماند.",
        vary_code="changed = batch.clone(); changed[1,0] += 100\nprint('centered change:',(changed-changed.mean(-1,keepdim=True))-(batch-batch.mean(-1,keepdim=True)))",
        debug="نسخهٔ خراب پیش از صاف‌کردن، B و T را جابه‌جا کرده است. تابع pack_batch_time(x) فقط (B,T,C) را با ترتیب b*T+t به (B*T,C) ببرد.",
        bug_code="wrong = batch.transpose(0,1).reshape(-1,3)\nprint('wrong row 1:',wrong[1],'expected source:',batch[0,1])",
        fix="def pack_batch_time(x):\n    # TODO\n    return None",
        fix_checks="result = pack_batch_time(batch)\nif result is None: return False\nassert torch.equal(result[1],batch[0,1])\nassert torch.equal(result[2],batch[1,0])\nx = torch.arange(30).reshape(2,3,5)\nassert torch.equal(pack_batch_time(x)[4],x[1,1])\nreturn True",
        fix_solution="def pack_batch_time(x):\n    return x.reshape(-1,x.shape[-1])",
        connection="MiniGPT در محاسبهٔ Loss دو محور Batch و Time را با همین ترتیب صاف می‌کند. درست‌بودن تعداد عناصر، ترتیب معنایی آن‌ها را تضمین نمی‌کند.",
        takeaway="کدام آزمون، جابه‌جایی خاموش نمونه و زمان را آشکار کرد؟",
    ),
    "04_gradients_steps": _lab(
        title="مشتق میانگین خطاهای یک Batch",
        goal="چند مسیر مشتق را جمع کنید و اثر میانگین‌گیری را از Learning rate جدا نگه دارید.",
        prerequisite="Autograd و پاک‌کردن Gradient را در همین دفتر دیده‌اید.",
        predict="برای دو نمونه، Gradientِ میانگین Lossها با جمع Gradientها چه نسبتی دارد؟ تکرار کل Batch باید میانگین Gradient را عوض کند؟",
        setup="features = torch.tensor([1.,3.])\ntargets = torch.tensor([2.,4.])\nprint('features/targets:',features,targets)",
        task="تابع batch_gradient(weight,features,targets) برای میانگین (weight*features-targets)^2 یک Gradient اسکالر با Autograd حساب و float برگرداند. weight ورودی عدد Python است؛ وزن را به‌روزرسانی نکنید.",
        starter="def batch_gradient(weight, features, targets):\n    # TODO\n    return None",
        checks="result = batch_gradient(1.,features,targets)\nif result is None: return False\nassert math.isclose(result,-4.)\nassert math.isclose(batch_gradient(1.,features.repeat(3),targets.repeat(3)),-4.)\na,b = torch.tensor([2.,-1.,3.]),torch.tensor([1.,2.,0.])\nexpected = (2*(0.5*a-b)*a).mean().item()\nassert math.isclose(batch_gradient(0.5,a,b),expected,rel_tol=1e-6)\nreturn True",
        solution="def batch_gradient(weight, features, targets):\n    w = torch.tensor(weight,requires_grad=True)\n    loss = ((w*features-targets)**2).mean()\n    return torch.autograd.grad(loss,w)[0].item()",
        vary="فقط Learning rate را تغییر دهید؛ همان Gradient اولیه را نگه دارید. این مقایسه یک گام است و دربارهٔ کل مسیر آموزش ادعایی ندارد.",
        vary_code="gradient = (2*(features-targets)*features).mean().item()\nfor learning_rate in (0.,0.1,0.5):\n    updated = 1.-learning_rate*gradient\n    print('learning rate, weight, next loss:',learning_rate,updated,((updated*features-targets)**2).mean().item())",
        debug="کد خراب برای میانگین Loss، Gradient جمع را به کار می‌برد. تابع mean_sample_gradients(gradients) را اصلاح کنید؛ فهرست ورودی غیرخالی است.",
        bug_code="sample_gradients = [-2.,-6.]\nprint('wrong sum:',sum(sample_gradients),'sample count:',len(sample_gradients))",
        fix="def mean_sample_gradients(gradients):\n    # TODO\n    return None",
        fix_checks="result = mean_sample_gradients(sample_gradients)\nif result is None: return False\nassert result == -4.\nassert mean_sample_gradients([2.,-2.,6.]) == 2.\nassert mean_sample_gradients([5.]) == 5.\nreturn True",
        fix_solution="def mean_sample_gradients(gradients):\n    return sum(gradients)/len(gradients)",
        connection="Loss پیش‌فرض MiniGPT میانگین موقعیت‌های Batch است. تغییر ناخواستهٔ mean به sum اندازهٔ Gradient را به تعداد هدف‌ها وابسته می‌کند، حتی اگر Learning rate ثابت بماند.",
        takeaway="چرا مقایسهٔ دو Learning rate بدون ثابت‌نگه‌داشتن قرارداد کاهش Loss می‌تواند گمراه‌کننده باشد؟",
    ),
    "05_first_network": _lab(
        title="دو Linear بدون Activation را در یکی خلاصه کنید",
        goal="با وزن و Bias واقعی نشان دهید زیادکردن لایه‌های خطی به‌تنهایی غیرخطی‌بودن نمی‌سازد.",
        prerequisite="نمونهٔ XOR و تفاوت Tanh با Identity در همین دفتر را دیده‌اید.",
        predict="اگر first از ۲ به ۴ ویژگی و last از ۴ به ۳ برود، وزن تبدیل ترکیبی چه شکل دارد؟ Bias اول پس از عبور از وزن دوم چه می‌شود؟",
        setup="from torch import nn\nfirst,last = nn.Linear(2,4),nn.Linear(4,3)\nx = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])\nprint('two-layer output:',last(first(x)).detach())",
        task="تابع collapse_linear(first,last) زوج (weight,bias) یک Linear هم‌ارز را برگرداند. میان این دو لایه Activation وجود ندارد؛ وزن‌های ورودی را تغییر ندهید.",
        starter="def collapse_linear(first, last):\n    # TODO\n    return None",
        checks="result = collapse_linear(first,last)\nif result is None: return False\nw,b = result\nassert w.shape == (3,2) and b.shape == (3,)\ntorch.testing.assert_close(x@w.T+b,last(first(x)))\na,c = nn.Linear(3,5),nn.Linear(5,2)\nz = torch.randn(2,4,3)\nw,b = collapse_linear(a,c)\ntorch.testing.assert_close(z@w.T+b,c(a(z)))\nreturn True",
        solution="def collapse_linear(first, last):\n    return last.weight@first.weight, last.weight@first.bias+last.bias",
        vary="فقط Tanh را بین همان دو لایه اضافه کنید؛ وزن‌ها ثابت بمانند. تبدیل ترکیبی قبلی دیگر همان مسیر نیست.",
        vary_code="with torch.no_grad():\n    affine = last(first(x))\n    nonlinear = last(torch.tanh(first(x)))\nprint('same weights, activation difference:',nonlinear-affine)",
        debug="نسخهٔ خراب Bias اول را حذف می‌کند. تابع composed_bias(first,last) فقط Bias صحیحِ ترکیب را برگرداند.",
        bug_code="with torch.no_grad():\n    first.bias.fill_(1.)\nwrong_bias = last.bias\nprint('lost contribution:',(last.weight@first.bias).detach())",
        fix="def composed_bias(first, last):\n    # TODO\n    return None",
        fix_checks="result = composed_bias(first,last)\nif result is None: return False\ntorch.testing.assert_close(result,last(first(torch.zeros(2))))\na,b = nn.Linear(1,2),nn.Linear(2,1)\ntorch.testing.assert_close(composed_bias(a,b),b(a(torch.zeros(1))))\nreturn True",
        fix_solution="def composed_bias(first, last):\n    return last.weight@first.bias+last.bias",
        connection="FFN در Transformer نیز دو Linear دارد، اما GELU میان آن‌ها اجازه نمی‌دهد کل مسیر را به این شیوه در یک Linear ثابت خلاصه کنیم.",
        takeaway="چرا افزایش تعداد Linearها، بدون Activation، پاسخ محدودیت شبکهٔ خطی روی XOR نیست؟",
    ),
    "06_tokens_embeddings": _lab(
        title="تکرار شناسه، جمع‌شدن سهم یک سطر",
        goal="از تعداد تکرار Tokenها، Gradient یک Embedding ساده را پیش‌بینی کنید.",
        prerequisite="Tokenizer و lookup و آزمایش sum در همین دفتر را دیده‌اید؛ این Loss هدف آموزش زبان نیست.",
        predict="اگر شناسهٔ ۱ سه بار و شناسهٔ ۲ یک بار دیده شود، مشتق sum خروجی نسبت به هر ویژگیِ این دو سطر چیست؟",
        setup="from torch import nn\nfrom mini_gpt.tokenizer import CharacterTokenizer\ntokenizer = CharacterTokenizer.from_text('سلام مدل')\nids = torch.tensor([[1,1,2],[3,1,2]])\nprint('IDs:',ids,'vocabulary size:',tokenizer.vocab_size)",
        task="تابع lookup_gradient_counts(ids,vocab_size,channels) مشتقِ پیش‌بینی‌شدهٔ embedding(ids).sum() را به شکل (V,C) برگرداند. بدون Autograd، تعداد حضور هر ID را در همهٔ ویژگی‌های همان سطر بگذارید.",
        starter="def lookup_gradient_counts(ids, vocab_size, channels):\n    # TODO\n    return None",
        checks="result = lookup_gradient_counts(ids,tokenizer.vocab_size,4)\nif result is None: return False\nfor tokens,C in ((ids,4),(torch.tensor([[0,2,0,2]]),3)):\n    table = nn.Embedding(tokenizer.vocab_size,C)\n    table(tokens).sum().backward()\n    torch.testing.assert_close(lookup_gradient_counts(tokens,tokenizer.vocab_size,C),table.weight.grad)\nassert torch.equal(result[1],torch.full((4,),3.))\nreturn True",
        solution="def lookup_gradient_counts(ids, vocab_size, channels):\n    counts = torch.bincount(ids.reshape(-1),minlength=vocab_size).float()\n    return counts[:,None].expand(vocab_size,channels).clone()",
        vary="فقط یک ID دیگر با مقدار ۱ اضافه کنید. برای این Loss خاص، همهٔ ویژگی‌های همان سطر یک واحد سهم بیشتر می‌گیرند؛ این قانون عمومی هر Loss زبانی نیست.",
        vary_code="before = torch.bincount(ids.flatten(),minlength=tokenizer.vocab_size)\nafter = torch.bincount(torch.cat((ids.flatten(),torch.tensor([1]))),minlength=tokenizer.vocab_size)\nprint('row count change:',after-before)",
        debug="نسخهٔ خراب ID صفر را از شمارش حذف می‌کند چون آن را «نبود داده» می‌پندارد. در Tokenizer پروژه، صفر سطر واقعی Unknown است. تابع count_all_ids(ids,vocab_size) همهٔ شناسه‌ها را بشمارد.",
        bug_code="unknown_ids = torch.tensor([0,1,0,2])\nprint('wrong: omitted unknown occurrences:',torch.bincount(unknown_ids[unknown_ids!=0],minlength=tokenizer.vocab_size))",
        fix="def count_all_ids(ids, vocab_size):\n    # TODO\n    return None",
        fix_checks="result = count_all_ids(unknown_ids,tokenizer.vocab_size)\nif result is None: return False\nassert result[0].item() == 2\nassert result.sum().item() == 4\nassert count_all_ids(torch.tensor([[2,2,1]]),4).tolist() == [0,1,2,0]\nreturn True",
        fix_solution="def count_all_ids(ids, vocab_size):\n    return torch.bincount(ids.reshape(-1),minlength=vocab_size)",
        connection="CharacterTokenizer واقعی، Unknown را با ID صفر نگه می‌دارد. Token Embedding این سطر را مانند سطرهای دیگر می‌خواند؛ شناسه‌ها Gradient ندارند، اما سطرهای خوانده‌شده می‌توانند داشته باشند.",
        takeaway="کدام ویژگیِ sum باعث شد Gradient هر سطر فقط به تعداد تکرار آن وابسته باشد؟ در Loss واقعی چه چیزی علاوه بر تعداد تکرار اثر دارد؟",
    ),
    "07_attention_math": _lab(
        title="اثر تغییر یک Value را پیش‌بینی کنید",
        goal="با Q/K ثابت، سهم دقیق یک منبع در همهٔ خروجی‌های Attention را حساب کنید.",
        prerequisite="مراحل امتیاز، Softmax و weights @ V همین دفتر را دیده‌اید.",
        predict="اگر فقط Valueِ موقعیت یک تغییر کند، کدام ستون از جدول وزن اندازهٔ اثر آن بر Queryهای مختلف را مشخص می‌کند؟",
        setup="scores = torch.tensor([[1.,0.,2.],[0.,2.,1.],[2.,1.,0.]])\nallowed = torch.ones(3,3,dtype=torch.bool).tril()\nweights = scores.masked_fill(~allowed,float('-inf')).softmax(-1)\nvalues = torch.tensor([[1.,0.],[0.,2.],[1.,2.]])\nprint('fixed weights:',weights)",
        task="تابع predict_value_delta(weights,key,delta) اختلاف خروجی همهٔ Queryها را وقتی فقط V[key] به اندازهٔ بردار delta عوض می‌شود، برگرداند. weights شکل (Q,S) و delta شکل (C,) است؛ Value اصلی برای این حساب لازم نیست.",
        starter="def predict_value_delta(weights, key, delta):\n    # TODO\n    return None",
        checks="delta = torch.tensor([2.,-1.])\nresult = predict_value_delta(weights,1,delta)\nif result is None: return False\nchanged = values.clone(); changed[1] += delta\ntorch.testing.assert_close(result,weights@changed-weights@values)\ntorch.testing.assert_close(result[0],torch.zeros(2))\nw = torch.tensor([[0.2,0.3,0.5],[1.,0.,0.]])\nd = torch.tensor([1.,2.,3.,4.])\ntorch.testing.assert_close(predict_value_delta(w,2,d),torch.stack((0.5*d,torch.zeros_like(d))))\nreturn True",
        solution="def predict_value_delta(weights, key, delta):\n    return weights[:,key,None]*delta",
        vary="فقط شمارهٔ Value تغییرکرده را میان صفر، یک و دو جابه‌جا کنید؛ بردار تغییر ثابت بماند. کدام خروجی‌ها به‌دلیل Mask دست‌نخورده می‌مانند؟",
        vary_code="delta = torch.tensor([2.,-1.])\nfor key in range(3):\n    changed = values.clone(); changed[key] += delta\n    print('changed key:',key,'output change:',weights@changed-weights@values)",
        debug="کد خراب به‌جای ستون Key، سطر Query را انتخاب می‌کند. تابع source_share(weights,key) سهم یک منبع در همهٔ Queryها را به شکل (Q,) برگرداند.",
        bug_code="print('wrong row for key 1:',weights[1])\nprint('each output needs the same source column')",
        fix="def source_share(weights, key):\n    # TODO\n    return None",
        fix_checks="result = source_share(weights,1)\nif result is None: return False\ntorch.testing.assert_close(result,weights[:,1])\nw = torch.tensor([[1.,2.,3.],[4.,5.,6.]])\ntorch.testing.assert_close(source_share(w,2),torch.tensor([3.,6.]))\nreturn True",
        fix_solution="def source_share(weights, key):\n    return weights[:,key]",
        connection="این رابطه دربارهٔ ضرب weights @ v در توجه پروژه است، وقتی وزن‌ها ثابت‌اند. اگر X را تغییر دهید، Q/K و وزن‌ها نیز ممکن است عوض شوند؛ آن آزمایش دیگر فقط تغییر Value نیست.",
        takeaway="چرا همین فرمول ساده را نمی‌توان بدون قید به تغییر یک Token ورودی نسبت داد؟",
    ),
    "08_causal_mask": _lab(
        title="نقشهٔ تجربی وابستگی موقعیت‌ها",
        goal="به‌جای فقط دیدن Mask، با تغییر تک‌تک ورودی‌ها مسیر اثر را اندازه بگیرید.",
        prerequisite="آزمون تغییر آینده و حالت eval در همین دفتر را بشناسید.",
        predict="در ماتریسی که سطرش موقعیت خروجی و ستونش ورودیِ تغییرکرده است، اثرهای مجاز یک مدل علّی در کدام سمت قطر قرار می‌گیرند؟",
        setup='''
        from mini_gpt.config import ModelConfig
        from mini_gpt.attention import CausalSelfAttention
        attention = CausalSelfAttention(ModelConfig(8,6,4,1,1,0.)).eval()
        with torch.no_grad():
            attention.qkv.weight.zero_(); attention.qkv.bias.zero_()
            attention.qkv.weight[8:].copy_(torch.eye(4))
            attention.output.weight.copy_(torch.eye(4)); attention.output.bias.zero_()
        x = torch.arange(16.).reshape(1,4,4)
        print("Controlled fixture: uniform allowed weights; identity Value/output")
        ''',
        task="تابع dependency_matrix(attention,x,causal=True) یک Tensor bool شکل (T,T) برگرداند. برای هر ستون j، فقط x[0,j,0] را یک واحد زیاد کنید؛ سطر i زمانی True باشد که بیشینهٔ تغییر ویژگی‌های خروجی i بیش از 1e-6 است. x را درجا تغییر ندهید؛ مدل همان شیء در eval است.",
        starter="def dependency_matrix(attention, x, causal=True):\n    # TODO\n    return None",
        checks="before = x.clone()\nresult = dependency_matrix(attention,x)\nif result is None: return False\nassert result.dtype == torch.bool\nassert torch.equal(result,torch.ones(4,4,dtype=torch.bool).tril())\nassert torch.equal(x,before)\nassert dependency_matrix(attention,x,causal=False).all()\nassert torch.equal(dependency_matrix(attention,x[:,:2]),torch.ones(2,2,dtype=torch.bool).tril())\nreturn True",
        solution="def dependency_matrix(attention, x, causal=True):\n    attention.eval()\n    with torch.no_grad():\n        original = attention(x,causal=causal)\n        columns = []\n        for j in range(x.shape[1]):\n            changed = x.clone(); changed[0,j,0] += 1\n            effect = (attention(changed,causal=causal)-original).abs().amax(-1)[0]\n            columns.append(effect > 1e-6)\n        return torch.stack(columns,dim=1)",
        vary="فقط causal را خاموش کنید و اثر تغییر آخرین ورودی را بسنجید. این وزن‌های کنترل‌شده عمداً مسیرهای مجاز را قابل مشاهده کرده‌اند؛ در یک مدل دلخواه نبودِ اثر عددی، نبودِ مسیر را ثابت نمی‌کند.",
        vary_code="changed = x.clone(); changed[0,-1,0] += 1\nwith torch.no_grad():\n    for causal in (False,True):\n        print(causal,(attention(changed,causal=causal)-attention(x,causal=causal)).abs().amax(-1))",
        debug="گزارش خراب سطر و ستون را برعکس تفسیر می‌کند و گذشته را نشت می‌نامد. تابع has_future_influence(matrix) با قرارداد سطر=خروجی، ستون=ورودیِ تغییرکرده، یک bool برگرداند.",
        bug_code="observed = torch.ones(4,4,dtype=torch.bool).tril()\nprint('wrong test of allowed past:',observed.tril(-1).any().item())",
        fix="def has_future_influence(matrix):\n    # TODO\n    return None",
        fix_checks="result = has_future_influence(observed)\nif result is None: return False\nassert result is False\nassert has_future_influence(torch.ones(3,3,dtype=torch.bool)) is True\nassert has_future_influence(torch.eye(3,dtype=torch.bool)) is False\nreturn True",
        fix_solution="def has_future_influence(matrix):\n    return matrix.triu(1).any().item()",
        connection="آزمایش روی CausalSelfAttention واقعی انجام شد. نقشهٔ وابستگی، مکمل trace وزن‌هاست؛ معنی هر دو محور باید در هر دو نمایش ثابت بماند.",
        takeaway="اگر در یک مدل آموزش‌دیده یک خانهٔ مجاز اثر عددی صفر داشت، چرا نباید فوراً نتیجه بگیریم مسیر آن در معماری وجود ندارد؟",
    ),
    "09_multi_head": _lab(
        title="سهم هر Head پس از Projection نهایی",
        goal="خروجی چندسر را به سهم‌های خطی Headها تجزیه کنید، بدون چندبار افزودن Bias.",
        prerequisite="تقسیم، ادغام و Output projection همین دفتر را بشناسید.",
        predict="Projection نهایی روی ویژگی‌های چسبانده‌شده عمل می‌کند. آیا می‌توان سهم هر قطعه را جدا ضرب کرد و جمع زد؟ Bias باید چند بار اضافه شود؟",
        setup="from mini_gpt.config import ModelConfig\nfrom mini_gpt.attention import CausalSelfAttention\nattention = CausalSelfAttention(ModelConfig(9,6,6,2,1,0.)).eval()\nwith torch.no_grad(): attention.output.bias.fill_(0.4)\nx = torch.randn(1,3,6)\ntrace = {}\nwith torch.no_grad(): output = attention(x,trace=trace)\nattended = trace['weighted_values']\nprint('per-head tensor:',attended.shape)",
        task="تابع head_contributions(attention,attended) شکل (B,H,T,C) برگرداند. برای هر Head فقط ستون‌های متناظر آن را از attention.output.weight بگیرید و سهم بدون Bias را حساب کنید. مجموع روی H به‌اضافهٔ یک Bias باید خروجی اصلی را بسازد.",
        starter="def head_contributions(attention, attended):\n    # TODO\n    return None",
        checks="result = head_contributions(attention,attended)\nif result is None: return False\nassert result.shape == (1,2,3,6)\ntorch.testing.assert_close(result.sum(1)+attention.output.bias,output)\nother = CausalSelfAttention(ModelConfig(9,6,6,3,1,0.)).eval()\na = torch.randn(2,3,4,2)\npieces = head_contributions(other,a)\nmerged = a.transpose(1,2).reshape(2,4,6)\ntorch.testing.assert_close(pieces.sum(1)+other.output.bias,other.output(merged))\nfor h in range(3):\n    torch.testing.assert_close(pieces[:,h],a[:,h]@other.output.weight[:,2*h:2*h+2].T)\nreturn True",
        solution="def head_contributions(attention, attended):\n    B,H,T,D = attended.shape\n    pieces = [attended[:,h]@attention.output.weight[:,h*D:(h+1)*D].T for h in range(H)]\n    return torch.stack(pieces,dim=1)",
        vary="فقط خروجی Head صفر را پیش از ادغام صفر کنید؛ وزن‌ها ثابت‌اند. این حذف مسیر عددی است، نه شاهدی دربارهٔ نقش زبانی یا اهمیت آموختهٔ آن Head.",
        vary_code="removed = attended.clone(); removed[:,0] = 0\nwith torch.no_grad():\n    changed_output = attention.output(removed.transpose(1,2).reshape(1,3,6))\nprint('head-zero removal effect:',output-changed_output)",
        debug="نسخهٔ خراب Bias را به سهم تک‌تک Headها اضافه می‌کند. تابع combine_contributions(pieces,bias) باید سهم‌ها را روی محور H جمع و Bias را یک بار اضافه کند.",
        bug_code="pieces = torch.ones(1,2,3,6)\nbias = torch.full((6,),0.4)\nprint('wrong repeated bias:',(pieces+bias).sum(1)[0,0])",
        fix="def combine_contributions(pieces, bias):\n    # TODO\n    return None",
        fix_checks="result = combine_contributions(pieces,bias)\nif result is None: return False\ntorch.testing.assert_close(result,torch.full((1,3,6),2.4))\na = torch.arange(24.).reshape(1,3,2,4)\nb = torch.tensor([1.,2.,3.,4.])\ntorch.testing.assert_close(combine_contributions(a,b),a[:,0]+a[:,1]+a[:,2]+b)\nreturn True",
        fix_solution="def combine_contributions(pieces, bias):\n    return pieces.sum(1)+bias",
        connection="این تجزیه دقیقاً از وزن output در CausalSelfAttention استفاده می‌کند. جمع سهم‌ها یک خاصیت Linear است؛ وزن Attention هر Head قبلاً در attended مصرف شده است.",
        takeaway="چرا نقش Output projection بیشتر از کنار هم چیدن Headهاست، حتی وقتی می‌توان آن را به سهم‌های خطی تجزیه کرد؟",
    ),
    "10_block_trace": _lab(
        title="همان وزن‌ها، ترتیب متفاوتِ Normalization",
        goal="تفاوت Pre-Norm و یک مسیر Post-Norm را با کنترل وزن‌ها بررسی کنید.",
        prerequisite="دو جمع و محل norm_1/norm_2 در بلوک واقعی این دفتر را دنبال کرده باشید.",
        predict="اگر LayerNorm را از ورودی زیرلایه به بعد از جمع منتقل کنیم، Shape تغییر می‌کند؟ آیا همان عددها را انتظار داریم؟",
        setup="from copy import deepcopy\nfrom mini_gpt.config import ModelConfig\nfrom mini_gpt.transformer import TransformerBlock\nconfig = ModelConfig(12,8,8,2,1,0.)\nblock = TransformerBlock(config).eval()\nx = torch.randn(2,4,8)\nprint('actual project architecture: Pre-Norm')",
        task="تابع postnorm_candidate(block,x) این مسیر مقایسه‌ای را با همان زیرلایه‌ها بسازد: y=norm_1(x+attention(x)) و out=norm_2(y+feed_forward(y)). این تابع معماری پروژه نیست؛ هدف دیدن اثر ترتیب است، نه اصلاح TransformerBlock.",
        starter="def postnorm_candidate(block, x):\n    # TODO\n    return None",
        checks="result = postnorm_candidate(block,x)\nif result is None: return False\ny = block.norm_1(x+block.attention(x))\ntorch.testing.assert_close(result,block.norm_2(y+block.feed_forward(y)))\nassert result.shape == x.shape\nzero = deepcopy(block)\nwith torch.no_grad():\n    for sublayer in (zero.attention,zero.feed_forward):\n        for parameter in sublayer.parameters(): parameter.zero_()\ntorch.testing.assert_close(postnorm_candidate(zero,x),zero.norm_2(zero.norm_1(x)))\nz = torch.randn(1,1,8)\na = block.norm_1(z+block.attention(z))\ntorch.testing.assert_close(postnorm_candidate(block,z),block.norm_2(a+block.feed_forward(a)))\nreturn True",
        solution="def postnorm_candidate(block, x):\n    y = block.norm_1(x+block.attention(x))\n    return block.norm_2(y+block.feed_forward(y))",
        vary="فقط ترتیب Normalization را عوض کنید؛ هیچ لایه یا وزن تازه‌ای نسازید. اختلاف این اجرا دربارهٔ کیفیت آموزش دو معماری داوری نمی‌کند.",
        vary_code="with torch.no_grad():\n    pre = block(x)\n    y = block.norm_1(x+block.attention(x))\n    post = block.norm_2(y+block.feed_forward(y))\nprint('same shape:',pre.shape == post.shape,'ordering difference:',(pre-post).abs().mean().item())",
        debug="مقایسهٔ دو بلوکِ تازه، اثر ترتیب را با تفاوت وزن‌ها مخلوط می‌کند. تابع align_weights(reference,candidate) state_dict مرجع را در نامزد بارگذاری و candidate را برگرداند؛ دو شیء همچنان مستقل بمانند.",
        bug_code="candidate = TransformerBlock(config).eval()\nprint('uncontrolled weight difference:',(candidate.attention.qkv.weight-block.attention.qkv.weight).abs().max().item())",
        fix="def align_weights(reference, candidate):\n    # TODO\n    return None",
        fix_checks="result = align_weights(block,candidate)\nif result is None: return False\nassert result is candidate and result is not block\nfor name,value in block.state_dict().items():\n    assert torch.equal(value,candidate.state_dict()[name])\nassert candidate.attention.qkv.weight is not block.attention.qkv.weight\ntorch.testing.assert_close(candidate(x),block(x))\nreturn True",
        fix_solution="def align_weights(reference, candidate):\n    candidate.load_state_dict(reference.state_dict())\n    return candidate",
        connection="TransformerBlock پروژه Pre-Norm باقی می‌ماند. آزمایش مقایسه‌ای از همان قطعه‌ها استفاده کرد تا نام معماری به محل دقیق عمل‌ها وصل شود؛ هیچ فایل تولیدی تغییر نکرد.",
        takeaway="برای نسبت‌دادن اختلاف خروجی به ترتیب لایه‌ها، چه عامل‌هایی را در این مقایسه ثابت نگه داشتید؟",
    ),
    "11_train_inspect": _lab(
        title="بعد از step دقیقاً کدام وزن‌ها تغییر کردند؟",
        goal="یک گزارش تغییر پارامتر بسازید و Snapshot واقعی را از نمای مشترک حافظه جدا کنید.",
        prerequisite="حلقهٔ آموزش و مقایسهٔ قبل/بعد از Optimizer step همین دفتر را دیده‌اید.",
        predict="آیا parameter.detach() به‌تنهایی عکس ثابتی از وزن می‌سازد؟ اگر وزن درجا عوض شود، آن Tensor چه می‌بیند؟",
        setup='''
        from mini_gpt.config import ModelConfig
        from mini_gpt.model import MiniGPT
        config = ModelConfig(9,6,8,2,1,0.)
        model = MiniGPT(config).eval()
        ids,targets = torch.tensor([[1,2,3],[2,3,4]]),torch.tensor([[2,3,4],[3,4,5]])
        initial_state = {name:value.detach().clone() for name,value in model.state_dict().items()}
        before = {name:p.detach().clone() for name,p in model.named_parameters()}
        optimizer = torch.optim.SGD(model.parameters(),lr=0.01)
        optimizer.zero_grad(set_to_none=True)
        model(ids,targets)[1].backward(); optimizer.step()
        after = {name:p.detach().clone() for name,p in model.named_parameters()}
        print("one controlled SGD step; no additional training run")
        ''',
        task="تابع parameter_changes(before,after) دیکشنری نام پارامتر به float اندازهٔ تغییر آن برگرداند؛ اندازه ریشهٔ مجموع مربع اختلاف همهٔ مؤلفه‌هاست. ورودی‌ها Snapshotهای هم‌کلیدند و نباید تغییر کنند.",
        starter="def parameter_changes(before, after):\n    # TODO\n    return None",
        checks="result = parameter_changes(before,after)\nif result is None: return False\nassert set(result) == set(before)\nfor name in before:\n    assert math.isclose(result[name],(after[name]-before[name]).norm().item(),abs_tol=1e-8)\nassert result['language_model_head.weight'] > 0\na = {'matrix':torch.zeros(2,2),'same':torch.ones(1)}\nb = {'matrix':torch.tensor([[3.,0.],[0.,4.]]),'same':torch.ones(1)}\nassert parameter_changes(a,b) == {'matrix':5.,'same':0.}\nreturn True",
        solution="def parameter_changes(before, after):\n    return {name:(after[name]-before[name]).norm().item() for name in before}",
        vary="فقط Learning rate یک گام SGD را از صفر به ۰٫۰۱ و ۰٫۰۲ تغییر دهید. هر اجرا از همان initial_state، همان Batch و Dropout صفر آغاز شود.",
        vary_code="for rate in (0.,0.01,0.02):\n    candidate = MiniGPT(config).eval(); candidate.load_state_dict(initial_state)\n    original = candidate.language_model_head.weight.detach().clone()\n    optimizer = torch.optim.SGD(candidate.parameters(),lr=rate)\n    candidate(ids,targets)[1].backward(); optimizer.step()\n    print('rate, head update norm:',rate,(candidate.language_model_head.weight-original).norm().item())",
        debug="Snapshot خراب فقط detach شده و حافظه را با پارامتر شریک است. تابع snapshot_parameters(model) برای هر named_parameter یک نسخهٔ مستقل و جدا از Graph بسازد.",
        bug_code="wrong_snapshot = model.token_embedding.weight.detach()\nwith torch.no_grad(): model.token_embedding.weight.add_(0.1)\nprint('wrong reported change:',(model.token_embedding.weight-wrong_snapshot).abs().max().item())",
        fix="def snapshot_parameters(model):\n    # TODO\n    return None",
        fix_checks="result = snapshot_parameters(model)\nif result is None: return False\nassert set(result) == {name for name,_ in model.named_parameters()}\nfor name,p in model.named_parameters():\n    assert not result[name].requires_grad\n    assert result[name].data_ptr() != p.data_ptr()\n    assert torch.equal(result[name],p)\nsaved = result['token_embedding.weight'].clone()\nwith torch.no_grad(): model.token_embedding.weight.add_(0.2)\nassert torch.equal(result['token_embedding.weight'],saved)\nreturn True",
        fix_solution="def snapshot_parameters(model):\n    return {name:p.detach().clone() for name,p in model.named_parameters()}",
        connection="گزارش از MiniGPT واقعی و یک step واقعی گرفته شد. تغییر وزن شاهد اجرای به‌روزرسانی است، ولی به‌تنهایی کاهش Validation Loss یا بهترشدن زبان را ثابت نمی‌کند.",
        takeaway="چرا گزارش «هیچ وزنی تغییر نکرد» ممکن است خطای ابزار اندازه‌گیری باشد، نه خطای Optimizer؟",
    ),
    "12_sampling": _lab(
        title="احتمال با فراوانی یک اجرای کوتاه یکی نیست",
        goal="از توزیع واقعی Sampling نمونه بگیرید و فراوانی‌ها را بدون ادعای برابری دقیق بررسی کنید.",
        prerequisite="Temperature، Top-K و توزیع گام اول در همین دفتر را بشناسید.",
        predict="اگر یک Token احتمال صفر داشته باشد، آیا باید در شمارش دیده شود؟ آیا Token با احتمال ۰٫۲ در ۱۰ نمونه حتماً دو بار ظاهر می‌شود؟",
        setup="from mini_gpt.sampling import sampling_distribution\nlogits = torch.tensor([[2.,1.,0.,-1.]])\nprobabilities = sampling_distribution(logits,top_k=3)[0]\nprint('fixed one-step distribution:',probabilities)",
        task="تابع sample_counts(probabilities,draws,generator) با torch.multinomial و replacement=True نمونه بگیرد و یک Tensor شمارش طول V برگرداند. probabilities یک بردار است؛ این‌ها تکرارِ مستقلِ همان گام ثابت‌اند، نه تولید یک دنبالهٔ جدید.",
        starter="def sample_counts(probabilities, draws, generator):\n    # TODO\n    return None",
        checks="result = sample_counts(probabilities,100,torch.Generator().manual_seed(23))\nif result is None: return False\nassert result.shape == probabilities.shape and result.sum().item() == 100\nassert result[-1].item() == 0\nexpected_ids = torch.multinomial(probabilities,100,replacement=True,generator=torch.Generator().manual_seed(23))\nassert torch.equal(result,torch.bincount(expected_ids,minlength=4))\nassert sample_counts(torch.tensor([0.,1.,0.]),7,torch.Generator().manual_seed(2)).tolist() == [0,7,0]\nreturn True",
        solution="def sample_counts(probabilities, draws, generator):\n    ids = torch.multinomial(probabilities,draws,replacement=True,generator=generator)\n    return torch.bincount(ids,minlength=probabilities.numel())",
        vary="فقط تعداد نمونه‌ها را از ۲۰ به ۲۰۰ و ۲۰۰۰ تغییر دهید. اختلاف تجربی را گزارش کنید؛ نزدیک‌شدن معمول را با کاهش قطعی و یکنواخت خطا در هر اجرای تصادفی اشتباه نگیرید.",
        vary_code="for draws in (20,200,2000):\n    sampled = torch.multinomial(probabilities,draws,replacement=True,generator=torch.Generator().manual_seed(31))\n    frequency = torch.bincount(sampled,minlength=4).float()/draws\n    print('draws, frequency, maximum error:',draws,frequency,(frequency-probabilities).abs().max().item())",
        debug="کد خراب argmax را بارها تکرار می‌کند و آن را Sampling می‌نامد. تابع draw_ids(probabilities,draws,generator) شناسه‌های نمونه‌برداری‌شده را برگرداند؛ از Seed داده‌شده استفاده کنید.",
        bug_code="wrong = probabilities.argmax().repeat(20)\nprint('greedy is not repeated random sampling:',torch.bincount(wrong,minlength=4))",
        fix="def draw_ids(probabilities, draws, generator):\n    # TODO\n    return None",
        fix_checks="result = draw_ids(probabilities,40,torch.Generator().manual_seed(7))\nif result is None: return False\nexpected = torch.multinomial(probabilities,40,replacement=True,generator=torch.Generator().manual_seed(7))\nassert torch.equal(result,expected)\nassert draw_ids(torch.tensor([0.,0.,1.]),3,torch.Generator().manual_seed(1)).tolist() == [2,2,2]\nreturn True",
        fix_solution="def draw_ids(probabilities, draws, generator):\n    return torch.multinomial(probabilities,draws,replacement=True,generator=generator)",
        connection="توزیع از sampling_distribution واقعی پروژه گرفته شد. در generate پس از هر انتخاب، Context و Logits دوباره تغییر می‌کنند؛ پس فراوانی Tokenهای یک متن بلند، آزمایش همین توزیع ثابت نیست.",
        takeaway="برای مقایسهٔ منصفانهٔ قانون انتخاب، چرا دفتر ابتدا یک مجموعه Logits ثابت را بررسی می‌کند و بعد سراغ ادامهٔ متن می‌رود؟",
    ),
}
