"""Author-only deterministic curriculum/workload inventory; never launches code."""
import argparse
import json
from pathlib import Path

from book_src.curriculum import LESSONS, CHAPTERS, PATHS, LEGACY_PATHS
from book_src.schema import PARTS
from book_src.learning_time import estimate, aggregate, duration
from book_src.laboratories import catalog


ROOT = Path(__file__).resolve().parents[1]


def inventory():
    labs = catalog(ROOT)
    return {
        'lessons': len(LESSONS), 'parts': len(PARTS), 'chapters': len(CHAPTERS),
        'checkpoints': len(PARTS), 'progress_units': len(LESSONS)+len(PARTS),
        'notebooks': len(labs), 'legacy_urls_preserved': len(LEGACY_PATHS),
        'new_lessons': [l.id for l in LESSONS if l.id not in LEGACY_PATHS],
        'total_minutes': aggregate(LESSONS, checkpoints=range(1,len(PARTS)+1)),
        'part_inventory': [
            {'part': n, 'title': title, 'lessons': len([l for l in LESSONS if l.part==n]),
             'minutes': aggregate([l for l in LESSONS if l.part==n],checkpoints=[n])}
            for n,(title,_) in enumerate(PARTS,1)],
        'lesson_inventory': [dict(id=l.id, part=l.part, chapter=l.chapter,
                                  path=PATHS[l.id], **estimate(l)) for l in LESSONS],
    }


def markdown(data):
    text = ('# Current curriculum and time inventory\n\n'
            'Generated by `python -m tools.journey_report`; source: '
            '`book_src/curriculum.py` and `book_src/learning_time.py`. '
            'Estimates are editorial planning ranges, not learner measurements.\n\n')
    text += (f"{data['lessons']} lessons; {data['chapters']} chapters; {data['parts']} parts; "
             f"{data['checkpoints']} checkpoints; {data['progress_units']} progress units; "
             f"{data['notebooks']} notebooks. All {data['legacy_urls_preserved']} prior lesson URLs preserved.\n\n")
    text += '**Core path including checkpoints: '+duration(data['total_minutes'],hours=True)+'.**\n\n'
    text += '| Part | Title | Lessons | Minutes (exact endpoints) | Display range |\n| --- | --- | --- | --- | --- |\n'
    for part in data['part_inventory']:
        text += (f"| {part['part']} | {part['title']} | {part['lessons']} | "
                 f"{part['minutes'][0]}–{part['minutes'][1]} | {duration(part['minutes'],hours=True)} |\n")
    text += ('\nReading + comprehension + code tracing + notebook experiments/repair + '
             'self-check + prerequisite recall. Optional reviews, setup and long training '
             'runs are excluded. See [assumptions](LEARNING_TIME.md).\n\n'
             '## Lesson-level estimates\n\n'
             '| ID | Part | Activity profile | Minutes |\n| --- | --- | --- | --- |\n')
    for lesson in data['lesson_inventory']:
        text += f"| {lesson['id']} | {lesson['part']} | {lesson['profile']} | {lesson['minutes'][0]}–{lesson['minutes'][1]} |\n"
    return text


def main(check=False):
    data = inventory()
    content = markdown(data)
    path = ROOT/'docs/JOURNEY_INVENTORY.md'
    if check:
        if not path.is_file() or path.read_text(encoding='utf-8') != content:
            raise ValueError('Curriculum/time inventory is stale; regenerate it explicitly')
    else:
        path.write_text(content,encoding='utf-8')
        report = ROOT/'.verification/journey-inventory.json'
        report.parent.mkdir(exist_ok=True)
        report.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(json.dumps({k:v for k,v in data.items() if k not in ('part_inventory','lesson_inventory')},ensure_ascii=False))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    main(parser.parse_args().check)
